-- SMAE-aligned platillo seed (#84): ingredient `alimento_nombre` must exist in packaged alimentos.sql
-- AUTO-GENERATED structure: 100 curated combinaciones (reproducible pools from catalog).

DROP TABLE IF EXISTS seed_platillo_ingrediente CASCADE;
DROP TABLE IF EXISTS seed_platillo CASCADE;

CREATE TABLE seed_platillo (
  name varchar(255) PRIMARY KEY,
  description varchar(510),
  ingestas_sugeridas varchar(255)
);

CREATE TABLE seed_platillo_ingrediente (
  id BIGSERIAL PRIMARY KEY,
  platillo_name varchar(255) NOT NULL REFERENCES seed_platillo(name) ON DELETE CASCADE,
  alimento_nombre varchar(255) NOT NULL,
  alimento_id bigint,
  peso_neto integer NOT NULL,
  orden integer NOT NULL DEFAULT 1
);

INSERT INTO seed_platillo (name, description, ingestas_sugeridas) VALUES
('Huevos revueltos con tortilla', 'Huevo con tortilla de maíz y jitomate. Desayuno frecuente.', 'Desayuno'),
('Avena con leche y fruta', 'Avena cocida con leche descremada, plátano y manzana.', 'Desayuno'),
('Arroz con pollo y frijoles', 'Arroz cocido, pollo sin piel, frijoles, jitomate y aceite.', 'Comida'),
('Espagueti con brócoli', 'Pasta cocida con brócoli y aceite.', 'Comida,Cena'),
('Ensalada con aguacate', 'Lechuga, pepino, jitomate, aguacate hass y aceite de oliva.', 'Comida,Cena'),
('Frijoles con tortilla', 'Frijoles de olla enteros enlatados equivalentes con tortilla de maíz.', 'Comida'),
('Salmón con arroz integral', 'Arroz integral cocido, salmón cocido con aceite.', 'Comida,Cena'),
('Yoghur con fruta', 'Yoghur light con plátano y manzana (snack ligero).', 'Colacion'),
('Arroz con huevo, jitomate y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aceite.', 'Desayuno'),
('Arroz con huevo, jitomate y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aceite de oliva.', 'Comida'),
('Arroz con huevo, jitomate y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aguacate hass.', 'Comida,Cena'),
('Arroz con huevo, lechuga y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aceite.', 'Colacion'),
('Arroz con huevo, lechuga y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aceite de oliva.', 'Cena'),
('Arroz con huevo, lechuga y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aguacate hass.', 'Desayuno'),
('Arroz con huevo, brócoli y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aceite.', 'Comida'),
('Arroz con huevo, brócoli y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aceite de oliva.', 'Comida,Cena'),
('Arroz con huevo, brócoli y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aguacate hass.', 'Colacion'),
('Arroz con huevo, pepino y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aceite.', 'Cena'),
('Arroz con huevo, pepino y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aceite de oliva.', 'Desayuno'),
('Arroz con huevo, pepino y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aguacate hass.', 'Comida'),
('Arroz con huevo, calabacita y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aceite.', 'Comida,Cena'),
('Arroz con huevo, calabacita y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aceite de oliva.', 'Colacion'),
('Arroz con huevo, calabacita y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aguacate hass.', 'Cena'),
('Arroz con huevo, ejotes y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aceite.', 'Desayuno'),
('Arroz con huevo, ejotes y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aceite de oliva.', 'Comida'),
('Arroz con huevo, ejotes y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aguacate hass.', 'Comida,Cena'),
('Arroz con huevo, espárragos y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aceite.', 'Colacion'),
('Arroz con huevo, espárragos y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aceite de oliva.', 'Cena'),
('Arroz con huevo, espárragos y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aguacate hass.', 'Desayuno'),
('Arroz con huevo, champiñones y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aceite.', 'Comida'),
('Arroz con huevo, champiñones y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aceite de oliva.', 'Comida,Cena'),
('Arroz con huevo, champiñones y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aguacate hass.', 'Colacion'),
('Arroz con huevo cocido, jitomate y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aceite.', 'Cena'),
('Arroz con huevo cocido, jitomate y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aceite de oliva.', 'Desayuno'),
('Arroz con huevo cocido, jitomate y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aguacate hass.', 'Comida'),
('Arroz con huevo cocido, lechuga y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aceite.', 'Comida,Cena'),
('Arroz con huevo cocido, lechuga y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aceite de oliva.', 'Colacion'),
('Arroz con huevo cocido, lechuga y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aguacate hass.', 'Cena'),
('Arroz con huevo cocido, brócoli y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aceite.', 'Desayuno'),
('Arroz con huevo cocido, brócoli y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aceite de oliva.', 'Comida'),
('Arroz con huevo cocido, brócoli y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aguacate hass.', 'Comida,Cena'),
('Arroz con huevo cocido, pepino y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aceite.', 'Colacion'),
('Arroz con huevo cocido, pepino y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aceite de oliva.', 'Cena'),
('Arroz con huevo cocido, pepino y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aguacate hass.', 'Desayuno'),
('Arroz con huevo cocido, calabacita y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aceite.', 'Comida'),
('Arroz con huevo cocido, calabacita y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aceite de oliva.', 'Comida,Cena'),
('Arroz con huevo cocido, calabacita y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aguacate hass.', 'Colacion'),
('Arroz con huevo cocido, ejotes y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aceite.', 'Cena'),
('Arroz con huevo cocido, ejotes y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aceite de oliva.', 'Desayuno'),
('Arroz con huevo cocido, ejotes y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aguacate hass.', 'Comida'),
('Arroz con huevo cocido, espárragos y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aceite.', 'Comida,Cena'),
('Arroz con huevo cocido, espárragos y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aceite de oliva.', 'Colacion'),
('Arroz con huevo cocido, espárragos y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aguacate hass.', 'Cena'),
('Arroz con huevo cocido, champiñones y aceite', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aceite.', 'Desayuno'),
('Arroz con huevo cocido, champiñones y aceite de oliva', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aceite de oliva.', 'Comida'),
('Arroz con huevo cocido, champiñones y aguacate', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aguacate hass.', 'Comida,Cena'),
('Arroz con pollo cocido sin piel, jitomate y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aceite.', 'Colacion'),
('Arroz con pollo cocido sin piel, jitomate y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aceite de oliva.', 'Cena'),
('Arroz con pollo cocido sin piel, jitomate y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aguacate hass.', 'Desayuno'),
('Arroz con pollo cocido sin piel, lechuga y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aceite.', 'Comida'),
('Arroz con pollo cocido sin piel, lechuga y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aceite de oliva.', 'Comida,Cena'),
('Arroz con pollo cocido sin piel, lechuga y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aguacate hass.', 'Colacion'),
('Arroz con pollo cocido sin piel, brócoli y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aceite.', 'Cena'),
('Arroz con pollo cocido sin piel, brócoli y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aceite de oliva.', 'Desayuno'),
('Arroz con pollo cocido sin piel, brócoli y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aguacate hass.', 'Comida'),
('Arroz con pollo cocido sin piel, pepino y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aceite.', 'Comida,Cena'),
('Arroz con pollo cocido sin piel, pepino y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aceite de oliva.', 'Colacion'),
('Arroz con pollo cocido sin piel, pepino y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aguacate hass.', 'Cena'),
('Arroz con pollo cocido sin piel, calabacita y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aceite.', 'Desayuno'),
('Arroz con pollo cocido sin piel, calabacita y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aceite de oliva.', 'Comida'),
('Arroz con pollo cocido sin piel, calabacita y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aguacate hass.', 'Comida,Cena'),
('Arroz con pollo cocido sin piel, ejotes y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aceite.', 'Colacion'),
('Arroz con pollo cocido sin piel, ejotes y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aceite de oliva.', 'Cena'),
('Arroz con pollo cocido sin piel, ejotes y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aguacate hass.', 'Desayuno'),
('Arroz con pollo cocido sin piel, espárragos y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aceite.', 'Comida'),
('Arroz con pollo cocido sin piel, espárragos y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aceite de oliva.', 'Comida,Cena'),
('Arroz con pollo cocido sin piel, espárragos y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aguacate hass.', 'Colacion'),
('Arroz con pollo cocido sin piel, champiñones y aceite', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aceite.', 'Cena'),
('Arroz con pollo cocido sin piel, champiñones y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aceite de oliva.', 'Desayuno'),
('Arroz con pollo cocido sin piel, champiñones y aguacate', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aguacate hass.', 'Comida'),
('Arroz con pollo crudo, jitomate y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aceite.', 'Comida,Cena'),
('Arroz con pollo crudo, jitomate y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aceite de oliva.', 'Colacion'),
('Arroz con pollo crudo, jitomate y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aguacate hass.', 'Cena'),
('Arroz con pollo crudo, lechuga y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aceite.', 'Desayuno'),
('Arroz con pollo crudo, lechuga y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aceite de oliva.', 'Comida'),
('Arroz con pollo crudo, lechuga y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aguacate hass.', 'Comida,Cena'),
('Arroz con pollo crudo, brócoli y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aceite.', 'Colacion'),
('Arroz con pollo crudo, brócoli y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aceite de oliva.', 'Cena'),
('Arroz con pollo crudo, brócoli y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aguacate hass.', 'Desayuno'),
('Arroz con pollo crudo, pepino y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aceite.', 'Comida'),
('Arroz con pollo crudo, pepino y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aceite de oliva.', 'Comida,Cena'),
('Arroz con pollo crudo, pepino y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aguacate hass.', 'Colacion'),
('Arroz con pollo crudo, calabacita y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aceite.', 'Cena'),
('Arroz con pollo crudo, calabacita y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aceite de oliva.', 'Desayuno'),
('Arroz con pollo crudo, calabacita y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aguacate hass.', 'Comida'),
('Arroz con pollo crudo, ejotes y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aceite.', 'Comida,Cena'),
('Arroz con pollo crudo, ejotes y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aceite de oliva.', 'Colacion'),
('Arroz con pollo crudo, ejotes y aguacate', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aguacate hass.', 'Cena'),
('Arroz con pollo crudo, espárragos y aceite', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Espárragos crudos; Aceite.', 'Desayuno'),
('Arroz con pollo crudo, espárragos y aceite de oliva', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Espárragos crudos; Aceite de oliva.', 'Comida');

INSERT INTO seed_platillo_ingrediente (platillo_name, alimento_nombre, peso_neto, orden) VALUES
('Huevos revueltos con tortilla', 'Huevo entero fresco', 132, 1),
('Huevos revueltos con tortilla', 'Tortilla de maíz', 60, 2),
('Huevos revueltos con tortilla', 'Aceite', 5, 3),
('Huevos revueltos con tortilla', 'Jitomate', 56, 4),
('Avena con leche y fruta', 'Avena cocida', 164, 1),
('Avena con leche y fruta', 'Leche descremada', 245, 2),
('Avena con leche y fruta', 'Plátano', 54, 3),
('Avena con leche y fruta', 'Manzana', 106, 4),
('Arroz con pollo y frijoles', 'Arroz cocido', 188, 1),
('Arroz con pollo y frijoles', 'Pollo sin piel cocido', 120, 2),
('Arroz con pollo y frijoles', 'Frijol promedio cocido', 86, 3),
('Arroz con pollo y frijoles', 'Jitomate', 56, 4),
('Arroz con pollo y frijoles', 'Aceite', 5, 5),
('Espagueti con brócoli', 'Espagueti cocido', 138, 1),
('Espagueti con brócoli', 'Brócoli cocido', 184, 2),
('Espagueti con brócoli', 'Aceite de oliva', 5, 3),
('Ensalada con aguacate', 'Lechuga', 135, 1),
('Ensalada con aguacate', 'Pepino con cáscara rebanado', 104, 2),
('Ensalada con aguacate', 'Jitomate', 56, 3),
('Ensalada con aguacate', 'Aguacate hass', 58, 4),
('Ensalada con aguacate', 'Aceite de oliva', 5, 5),
('Frijoles con tortilla', 'Frijoles enteros enlatados', 128, 1),
('Frijoles con tortilla', 'Tortilla de maíz', 90, 2),
('Frijoles con tortilla', 'Jitomate', 56, 3),
('Salmón con arroz integral', 'Arroz integral cocido', 195, 1),
('Salmón con arroz integral', 'Salmón cocido', 90, 2),
('Salmón con arroz integral', 'Aceite', 5, 3),
('Yoghur con fruta', 'Yoghur light', 180, 1),
('Yoghur con fruta', 'Plátano', 54, 2),
('Yoghur con fruta', 'Manzana', 106, 3),
('Arroz con huevo, jitomate y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, jitomate y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, jitomate y aceite', 'Jitomate', 113, 3),
('Arroz con huevo, jitomate y aceite', 'Aceite', 10, 4),
('Arroz con huevo, jitomate y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, jitomate y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, jitomate y aceite de oliva', 'Jitomate', 113, 3),
('Arroz con huevo, jitomate y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, jitomate y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, jitomate y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, jitomate y aguacate', 'Jitomate', 113, 3),
('Arroz con huevo, jitomate y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, lechuga y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, lechuga y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, lechuga y aceite', 'Lechuga', 135, 3),
('Arroz con huevo, lechuga y aceite', 'Aceite', 10, 4),
('Arroz con huevo, lechuga y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, lechuga y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, lechuga y aceite de oliva', 'Lechuga', 135, 3),
('Arroz con huevo, lechuga y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, lechuga y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, lechuga y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, lechuga y aguacate', 'Lechuga', 135, 3),
('Arroz con huevo, lechuga y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, brócoli y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, brócoli y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, brócoli y aceite', 'Brócoli cocido', 92, 3),
('Arroz con huevo, brócoli y aceite', 'Aceite', 10, 4),
('Arroz con huevo, brócoli y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, brócoli y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, brócoli y aceite de oliva', 'Brócoli cocido', 92, 3),
('Arroz con huevo, brócoli y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, brócoli y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, brócoli y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, brócoli y aguacate', 'Brócoli cocido', 92, 3),
('Arroz con huevo, brócoli y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, pepino y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, pepino y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, pepino y aceite', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo, pepino y aceite', 'Aceite', 10, 4),
('Arroz con huevo, pepino y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, pepino y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, pepino y aceite de oliva', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo, pepino y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, pepino y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, pepino y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, pepino y aguacate', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo, pepino y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, calabacita y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, calabacita y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, calabacita y aceite', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo, calabacita y aceite', 'Aceite', 10, 4),
('Arroz con huevo, calabacita y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, calabacita y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, calabacita y aceite de oliva', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo, calabacita y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, calabacita y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, calabacita y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, calabacita y aguacate', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo, calabacita y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, ejotes y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, ejotes y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, ejotes y aceite', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo, ejotes y aceite', 'Aceite', 10, 4),
('Arroz con huevo, ejotes y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, ejotes y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, ejotes y aceite de oliva', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo, ejotes y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, ejotes y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, ejotes y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, ejotes y aguacate', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo, ejotes y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, espárragos y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, espárragos y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, espárragos y aceite', 'Espárragos crudos', 90, 3),
('Arroz con huevo, espárragos y aceite', 'Aceite', 10, 4),
('Arroz con huevo, espárragos y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, espárragos y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, espárragos y aceite de oliva', 'Espárragos crudos', 90, 3),
('Arroz con huevo, espárragos y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, espárragos y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, espárragos y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, espárragos y aguacate', 'Espárragos crudos', 90, 3),
('Arroz con huevo, espárragos y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo, champiñones y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo, champiñones y aceite', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, champiñones y aceite', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo, champiñones y aceite', 'Aceite', 10, 4),
('Arroz con huevo, champiñones y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo, champiñones y aceite de oliva', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, champiñones y aceite de oliva', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo, champiñones y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo, champiñones y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo, champiñones y aguacate', 'Huevo entero fresco', 44, 2),
('Arroz con huevo, champiñones y aguacate', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo, champiñones y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, jitomate y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, jitomate y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, jitomate y aceite', 'Jitomate', 113, 3),
('Arroz con huevo cocido, jitomate y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, jitomate y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, jitomate y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, jitomate y aceite de oliva', 'Jitomate', 113, 3),
('Arroz con huevo cocido, jitomate y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, jitomate y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, jitomate y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, jitomate y aguacate', 'Jitomate', 113, 3),
('Arroz con huevo cocido, jitomate y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, lechuga y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, lechuga y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, lechuga y aceite', 'Lechuga', 135, 3),
('Arroz con huevo cocido, lechuga y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, lechuga y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, lechuga y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, lechuga y aceite de oliva', 'Lechuga', 135, 3),
('Arroz con huevo cocido, lechuga y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, lechuga y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, lechuga y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, lechuga y aguacate', 'Lechuga', 135, 3),
('Arroz con huevo cocido, lechuga y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, brócoli y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, brócoli y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, brócoli y aceite', 'Brócoli cocido', 92, 3),
('Arroz con huevo cocido, brócoli y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, brócoli y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, brócoli y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, brócoli y aceite de oliva', 'Brócoli cocido', 92, 3),
('Arroz con huevo cocido, brócoli y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, brócoli y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, brócoli y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, brócoli y aguacate', 'Brócoli cocido', 92, 3),
('Arroz con huevo cocido, brócoli y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, pepino y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, pepino y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, pepino y aceite', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo cocido, pepino y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, pepino y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, pepino y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, pepino y aceite de oliva', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo cocido, pepino y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, pepino y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, pepino y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, pepino y aguacate', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con huevo cocido, pepino y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, calabacita y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, calabacita y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, calabacita y aceite', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo cocido, calabacita y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, calabacita y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, calabacita y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, calabacita y aceite de oliva', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo cocido, calabacita y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, calabacita y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, calabacita y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, calabacita y aguacate', 'Calabacita alargada cruda', 91, 3),
('Arroz con huevo cocido, calabacita y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, ejotes y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, ejotes y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, ejotes y aceite', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo cocido, ejotes y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, ejotes y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, ejotes y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, ejotes y aceite de oliva', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo cocido, ejotes y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, ejotes y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, ejotes y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, ejotes y aguacate', 'Ejotes cocidos picados', 63, 3),
('Arroz con huevo cocido, ejotes y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, espárragos y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, espárragos y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, espárragos y aceite', 'Espárragos crudos', 90, 3),
('Arroz con huevo cocido, espárragos y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, espárragos y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, espárragos y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, espárragos y aceite de oliva', 'Espárragos crudos', 90, 3),
('Arroz con huevo cocido, espárragos y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, espárragos y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, espárragos y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, espárragos y aguacate', 'Espárragos crudos', 90, 3),
('Arroz con huevo cocido, espárragos y aguacate', 'Aguacate hass', 58, 4),
('Arroz con huevo cocido, champiñones y aceite', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, champiñones y aceite', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, champiñones y aceite', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo cocido, champiñones y aceite', 'Aceite', 10, 4),
('Arroz con huevo cocido, champiñones y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, champiñones y aceite de oliva', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, champiñones y aceite de oliva', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo cocido, champiñones y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con huevo cocido, champiñones y aguacate', 'Arroz cocido', 75, 1),
('Arroz con huevo cocido, champiñones y aguacate', 'Huevo entero cocido', 44, 2),
('Arroz con huevo cocido, champiñones y aguacate', 'Champiñon cocido entero', 78, 3),
('Arroz con huevo cocido, champiñones y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, jitomate y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, jitomate y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, jitomate y aceite', 'Jitomate', 113, 3),
('Arroz con pollo cocido sin piel, jitomate y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, jitomate y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, jitomate y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, jitomate y aceite de oliva', 'Jitomate', 113, 3),
('Arroz con pollo cocido sin piel, jitomate y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, jitomate y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, jitomate y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, jitomate y aguacate', 'Jitomate', 113, 3),
('Arroz con pollo cocido sin piel, jitomate y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, lechuga y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, lechuga y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, lechuga y aceite', 'Lechuga', 135, 3),
('Arroz con pollo cocido sin piel, lechuga y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, lechuga y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, lechuga y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, lechuga y aceite de oliva', 'Lechuga', 135, 3),
('Arroz con pollo cocido sin piel, lechuga y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, lechuga y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, lechuga y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, lechuga y aguacate', 'Lechuga', 135, 3),
('Arroz con pollo cocido sin piel, lechuga y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, brócoli y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, brócoli y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, brócoli y aceite', 'Brócoli cocido', 92, 3),
('Arroz con pollo cocido sin piel, brócoli y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, brócoli y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, brócoli y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, brócoli y aceite de oliva', 'Brócoli cocido', 92, 3),
('Arroz con pollo cocido sin piel, brócoli y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, brócoli y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, brócoli y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, brócoli y aguacate', 'Brócoli cocido', 92, 3),
('Arroz con pollo cocido sin piel, brócoli y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, pepino y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, pepino y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, pepino y aceite', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo cocido sin piel, pepino y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, pepino y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, pepino y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, pepino y aceite de oliva', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo cocido sin piel, pepino y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, pepino y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, pepino y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, pepino y aguacate', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo cocido sin piel, pepino y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, calabacita y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, calabacita y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, calabacita y aceite', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo cocido sin piel, calabacita y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, calabacita y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, calabacita y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, calabacita y aceite de oliva', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo cocido sin piel, calabacita y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, calabacita y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, calabacita y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, calabacita y aguacate', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo cocido sin piel, calabacita y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, ejotes y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, ejotes y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, ejotes y aceite', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo cocido sin piel, ejotes y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, ejotes y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, ejotes y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, ejotes y aceite de oliva', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo cocido sin piel, ejotes y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, ejotes y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, ejotes y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, ejotes y aguacate', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo cocido sin piel, ejotes y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, espárragos y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, espárragos y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, espárragos y aceite', 'Espárragos crudos', 90, 3),
('Arroz con pollo cocido sin piel, espárragos y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, espárragos y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, espárragos y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, espárragos y aceite de oliva', 'Espárragos crudos', 90, 3),
('Arroz con pollo cocido sin piel, espárragos y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, espárragos y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, espárragos y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, espárragos y aguacate', 'Espárragos crudos', 90, 3),
('Arroz con pollo cocido sin piel, espárragos y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo cocido sin piel, champiñones y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, champiñones y aceite', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, champiñones y aceite', 'Champiñon cocido entero', 78, 3),
('Arroz con pollo cocido sin piel, champiñones y aceite', 'Aceite', 10, 4),
('Arroz con pollo cocido sin piel, champiñones y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, champiñones y aceite de oliva', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, champiñones y aceite de oliva', 'Champiñon cocido entero', 78, 3),
('Arroz con pollo cocido sin piel, champiñones y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo cocido sin piel, champiñones y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo cocido sin piel, champiñones y aguacate', 'Pollo sin piel cocido', 30, 2),
('Arroz con pollo cocido sin piel, champiñones y aguacate', 'Champiñon cocido entero', 78, 3),
('Arroz con pollo cocido sin piel, champiñones y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, jitomate y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, jitomate y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, jitomate y aceite', 'Jitomate', 113, 3),
('Arroz con pollo crudo, jitomate y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, jitomate y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, jitomate y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, jitomate y aceite de oliva', 'Jitomate', 113, 3),
('Arroz con pollo crudo, jitomate y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, jitomate y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, jitomate y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, jitomate y aguacate', 'Jitomate', 113, 3),
('Arroz con pollo crudo, jitomate y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, lechuga y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, lechuga y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, lechuga y aceite', 'Lechuga', 135, 3),
('Arroz con pollo crudo, lechuga y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, lechuga y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, lechuga y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, lechuga y aceite de oliva', 'Lechuga', 135, 3),
('Arroz con pollo crudo, lechuga y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, lechuga y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, lechuga y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, lechuga y aguacate', 'Lechuga', 135, 3),
('Arroz con pollo crudo, lechuga y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, brócoli y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, brócoli y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, brócoli y aceite', 'Brócoli cocido', 92, 3),
('Arroz con pollo crudo, brócoli y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, brócoli y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, brócoli y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, brócoli y aceite de oliva', 'Brócoli cocido', 92, 3),
('Arroz con pollo crudo, brócoli y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, brócoli y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, brócoli y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, brócoli y aguacate', 'Brócoli cocido', 92, 3),
('Arroz con pollo crudo, brócoli y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, pepino y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, pepino y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, pepino y aceite', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo crudo, pepino y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, pepino y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, pepino y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, pepino y aceite de oliva', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo crudo, pepino y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, pepino y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, pepino y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, pepino y aguacate', 'Pepino con cáscara rebanado', 104, 3),
('Arroz con pollo crudo, pepino y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, calabacita y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, calabacita y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, calabacita y aceite', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo crudo, calabacita y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, calabacita y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, calabacita y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, calabacita y aceite de oliva', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo crudo, calabacita y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, calabacita y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, calabacita y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, calabacita y aguacate', 'Calabacita alargada cruda', 91, 3),
('Arroz con pollo crudo, calabacita y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, ejotes y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, ejotes y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, ejotes y aceite', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo crudo, ejotes y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, ejotes y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, ejotes y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, ejotes y aceite de oliva', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo crudo, ejotes y aceite de oliva', 'Aceite de oliva', 10, 4),
('Arroz con pollo crudo, ejotes y aguacate', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, ejotes y aguacate', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, ejotes y aguacate', 'Ejotes cocidos picados', 63, 3),
('Arroz con pollo crudo, ejotes y aguacate', 'Aguacate hass', 58, 4),
('Arroz con pollo crudo, espárragos y aceite', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, espárragos y aceite', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, espárragos y aceite', 'Espárragos crudos', 90, 3),
('Arroz con pollo crudo, espárragos y aceite', 'Aceite', 10, 4),
('Arroz con pollo crudo, espárragos y aceite de oliva', 'Arroz cocido', 75, 1),
('Arroz con pollo crudo, espárragos y aceite de oliva', 'Pollo crudo sin piel', 26, 2),
('Arroz con pollo crudo, espárragos y aceite de oliva', 'Espárragos crudos', 90, 3),
('Arroz con pollo crudo, espárragos y aceite de oliva', 'Aceite de oliva', 10, 4);