-- SMAE-aligned platillo seed (#84): ingredient `alimento_nombre` must exist in packaged alimentos.sql
-- AUTO-GENERATED structure: 100 curated combinaciones (reproducible pools from catalog).

DROP TABLE IF EXISTS seed_platillo_ingrediente CASCADE;
DROP TABLE IF EXISTS seed_platillo CASCADE;

CREATE TABLE seed_platillo (
  name varchar(255) PRIMARY KEY,
  description varchar(510),
  ingestas_sugeridas varchar(255)
);

CREATE TABLE seed_platillo_ingrediente (
  id BIGSERIAL PRIMARY KEY,
  platillo_name varchar(255) NOT NULL REFERENCES seed_platillo(name) ON DELETE CASCADE,
  alimento_nombre varchar(255) NOT NULL,
  alimento_id bigint,
  peso_neto integer NOT NULL,
  orden integer NOT NULL DEFAULT 1
);

INSERT INTO seed_platillo (name, description, ingestas_sugeridas) VALUES
('Huevos revueltos con tortilla', 'Huevo con tortilla de maíz y jitomate. Desayuno frecuente.', 'Desayuno'),
('Avena con leche y fruta', 'Avena cocida con leche descremada, plátano y manzana.', 'Desayuno'),
('Arroz con pollo y frijoles', 'Arroz cocido, pollo sin piel, frijoles, jitomate y aceite.', 'Comida'),
('Espagueti con brócoli', 'Pasta cocida con brócoli y aceite.', 'Comida,Cena'),
('Ensalada con aguacate', 'Lechuga, pepino, jitomate, aguacate hass y aceite de oliva.', 'Comida,Cena'),
('Frijoles con tortilla', 'Frijoles de olla enteros enlatados equivalentes con tortilla de maíz.', 'Comida'),
('Salmón con arroz integral', 'Arroz integral cocido, salmón cocido con aceite.', 'Comida,Cena'),
('Yoghur con fruta', 'Yoghur light con plátano y manzana (snack ligero).', 'Colacion'),
('Modelo SMC 009', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aceite.', 'Desayuno'),
('Modelo SMC 010', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aceite de oliva.', 'Comida'),
('Modelo SMC 011', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Jitomate; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 012', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aceite.', 'Colacion'),
('Modelo SMC 013', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aceite de oliva.', 'Cena'),
('Modelo SMC 014', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Lechuga; Aguacate hass.', 'Desayuno'),
('Modelo SMC 015', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aceite.', 'Comida'),
('Modelo SMC 016', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 017', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Brócoli cocido; Aguacate hass.', 'Colacion'),
('Modelo SMC 018', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aceite.', 'Cena'),
('Modelo SMC 019', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 020', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Pepino con cáscara rebanado; Aguacate hass.', 'Comida'),
('Modelo SMC 021', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aceite.', 'Comida,Cena'),
('Modelo SMC 022', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aceite de oliva.', 'Colacion'),
('Modelo SMC 023', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Calabacita alargada cruda; Aguacate hass.', 'Cena'),
('Modelo SMC 024', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aceite.', 'Desayuno'),
('Modelo SMC 025', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aceite de oliva.', 'Comida'),
('Modelo SMC 026', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Ejotes cocidos picados; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 027', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aceite.', 'Colacion'),
('Modelo SMC 028', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aceite de oliva.', 'Cena'),
('Modelo SMC 029', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Espárragos crudos; Aguacate hass.', 'Desayuno'),
('Modelo SMC 030', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aceite.', 'Comida'),
('Modelo SMC 031', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 032', 'Combinación catálogo: Arroz cocido; Huevo entero fresco; Champiñon cocido entero; Aguacate hass.', 'Colacion'),
('Modelo SMC 033', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aceite.', 'Cena'),
('Modelo SMC 034', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 035', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Jitomate; Aguacate hass.', 'Comida'),
('Modelo SMC 036', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aceite.', 'Comida,Cena'),
('Modelo SMC 037', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aceite de oliva.', 'Colacion'),
('Modelo SMC 038', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Lechuga; Aguacate hass.', 'Cena'),
('Modelo SMC 039', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aceite.', 'Desayuno'),
('Modelo SMC 040', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aceite de oliva.', 'Comida'),
('Modelo SMC 041', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Brócoli cocido; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 042', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aceite.', 'Colacion'),
('Modelo SMC 043', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aceite de oliva.', 'Cena'),
('Modelo SMC 044', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Pepino con cáscara rebanado; Aguacate hass.', 'Desayuno'),
('Modelo SMC 045', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aceite.', 'Comida'),
('Modelo SMC 046', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 047', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Calabacita alargada cruda; Aguacate hass.', 'Colacion'),
('Modelo SMC 048', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aceite.', 'Cena'),
('Modelo SMC 049', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 050', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Ejotes cocidos picados; Aguacate hass.', 'Comida'),
('Modelo SMC 051', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aceite.', 'Comida,Cena'),
('Modelo SMC 052', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aceite de oliva.', 'Colacion'),
('Modelo SMC 053', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Espárragos crudos; Aguacate hass.', 'Cena'),
('Modelo SMC 054', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aceite.', 'Desayuno'),
('Modelo SMC 055', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aceite de oliva.', 'Comida'),
('Modelo SMC 056', 'Combinación catálogo: Arroz cocido; Huevo entero cocido; Champiñon cocido entero; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 057', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aceite.', 'Colacion'),
('Modelo SMC 058', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aceite de oliva.', 'Cena'),
('Modelo SMC 059', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Jitomate; Aguacate hass.', 'Desayuno'),
('Modelo SMC 060', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aceite.', 'Comida'),
('Modelo SMC 061', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 062', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Lechuga; Aguacate hass.', 'Colacion'),
('Modelo SMC 063', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aceite.', 'Cena'),
('Modelo SMC 064', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 065', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Brócoli cocido; Aguacate hass.', 'Comida'),
('Modelo SMC 066', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aceite.', 'Comida,Cena'),
('Modelo SMC 067', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aceite de oliva.', 'Colacion'),
('Modelo SMC 068', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Pepino con cáscara rebanado; Aguacate hass.', 'Cena'),
('Modelo SMC 069', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aceite.', 'Desayuno'),
('Modelo SMC 070', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aceite de oliva.', 'Comida'),
('Modelo SMC 071', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Calabacita alargada cruda; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 072', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aceite.', 'Colacion'),
('Modelo SMC 073', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aceite de oliva.', 'Cena'),
('Modelo SMC 074', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Ejotes cocidos picados; Aguacate hass.', 'Desayuno'),
('Modelo SMC 075', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aceite.', 'Comida'),
('Modelo SMC 076', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 077', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Espárragos crudos; Aguacate hass.', 'Colacion'),
('Modelo SMC 078', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aceite.', 'Cena'),
('Modelo SMC 079', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 080', 'Combinación catálogo: Arroz cocido; Pollo sin piel cocido; Champiñon cocido entero; Aguacate hass.', 'Comida'),
('Modelo SMC 081', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aceite.', 'Comida,Cena'),
('Modelo SMC 082', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aceite de oliva.', 'Colacion'),
('Modelo SMC 083', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Jitomate; Aguacate hass.', 'Cena'),
('Modelo SMC 084', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aceite.', 'Desayuno'),
('Modelo SMC 085', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aceite de oliva.', 'Comida'),
('Modelo SMC 086', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Lechuga; Aguacate hass.', 'Comida,Cena'),
('Modelo SMC 087', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aceite.', 'Colacion'),
('Modelo SMC 088', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aceite de oliva.', 'Cena'),
('Modelo SMC 089', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Brócoli cocido; Aguacate hass.', 'Desayuno'),
('Modelo SMC 090', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aceite.', 'Comida'),
('Modelo SMC 091', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aceite de oliva.', 'Comida,Cena'),
('Modelo SMC 092', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Pepino con cáscara rebanado; Aguacate hass.', 'Colacion'),
('Modelo SMC 093', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aceite.', 'Cena'),
('Modelo SMC 094', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aceite de oliva.', 'Desayuno'),
('Modelo SMC 095', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Calabacita alargada cruda; Aguacate hass.', 'Comida'),
('Modelo SMC 096', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aceite.', 'Comida,Cena'),
('Modelo SMC 097', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aceite de oliva.', 'Colacion'),
('Modelo SMC 098', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Ejotes cocidos picados; Aguacate hass.', 'Cena'),
('Modelo SMC 099', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Espárragos crudos; Aceite.', 'Desayuno'),
('Modelo SMC 100', 'Combinación catálogo: Arroz cocido; Pollo crudo sin piel; Espárragos crudos; Aceite de oliva.', 'Comida');

INSERT INTO seed_platillo_ingrediente (platillo_name, alimento_nombre, peso_neto, orden) VALUES
('Huevos revueltos con tortilla', 'Huevo entero fresco', 132, 1),
('Huevos revueltos con tortilla', 'Tortilla de maíz', 60, 2),
('Huevos revueltos con tortilla', 'Aceite', 5, 3),
('Huevos revueltos con tortilla', 'Jitomate', 56, 4),
('Avena con leche y fruta', 'Avena cocida', 164, 1),
('Avena con leche y fruta', 'Leche descremada', 245, 2),
('Avena con leche y fruta', 'Plátano', 54, 3),
('Avena con leche y fruta', 'Manzana', 106, 4),
('Arroz con pollo y frijoles', 'Arroz cocido', 188, 1),
('Arroz con pollo y frijoles', 'Pollo sin piel cocido', 120, 2),
('Arroz con pollo y frijoles', 'Frijol promedio cocido', 86, 3),
('Arroz con pollo y frijoles', 'Jitomate', 56, 4),
('Arroz con pollo y frijoles', 'Aceite', 5, 5),
('Espagueti con brócoli', 'Espagueti cocido', 138, 1),
('Espagueti con brócoli', 'Brócoli cocido', 184, 2),
('Espagueti con brócoli', 'Aceite de oliva', 5, 3),
('Ensalada con aguacate', 'Lechuga', 135, 1),
('Ensalada con aguacate', 'Pepino con cáscara rebanado', 104, 2),
('Ensalada con aguacate', 'Jitomate', 56, 3),
('Ensalada con aguacate', 'Aguacate hass', 58, 4),
('Ensalada con aguacate', 'Aceite de oliva', 5, 5),
('Frijoles con tortilla', 'Frijoles enteros enlatados', 128, 1),
('Frijoles con tortilla', 'Tortilla de maíz', 90, 2),
('Frijoles con tortilla', 'Jitomate', 56, 3),
('Salmón con arroz integral', 'Arroz integral cocido', 195, 1),
('Salmón con arroz integral', 'Salmón cocido', 90, 2),
('Salmón con arroz integral', 'Aceite', 5, 3),
('Yoghur con fruta', 'Yoghur light', 180, 1),
('Yoghur con fruta', 'Plátano', 54, 2),
('Yoghur con fruta', 'Manzana', 106, 3),
('Modelo SMC 009', 'Arroz cocido', 75, 1),
('Modelo SMC 009', 'Huevo entero fresco', 44, 2),
('Modelo SMC 009', 'Jitomate', 113, 3),
('Modelo SMC 009', 'Aceite', 10, 4),
('Modelo SMC 010', 'Arroz cocido', 75, 1),
('Modelo SMC 010', 'Huevo entero fresco', 44, 2),
('Modelo SMC 010', 'Jitomate', 113, 3),
('Modelo SMC 010', 'Aceite de oliva', 10, 4),
('Modelo SMC 011', 'Arroz cocido', 75, 1),
('Modelo SMC 011', 'Huevo entero fresco', 44, 2),
('Modelo SMC 011', 'Jitomate', 113, 3),
('Modelo SMC 011', 'Aguacate hass', 58, 4),
('Modelo SMC 012', 'Arroz cocido', 75, 1),
('Modelo SMC 012', 'Huevo entero fresco', 44, 2),
('Modelo SMC 012', 'Lechuga', 135, 3),
('Modelo SMC 012', 'Aceite', 10, 4),
('Modelo SMC 013', 'Arroz cocido', 75, 1),
('Modelo SMC 013', 'Huevo entero fresco', 44, 2),
('Modelo SMC 013', 'Lechuga', 135, 3),
('Modelo SMC 013', 'Aceite de oliva', 10, 4),
('Modelo SMC 014', 'Arroz cocido', 75, 1),
('Modelo SMC 014', 'Huevo entero fresco', 44, 2),
('Modelo SMC 014', 'Lechuga', 135, 3),
('Modelo SMC 014', 'Aguacate hass', 58, 4),
('Modelo SMC 015', 'Arroz cocido', 75, 1),
('Modelo SMC 015', 'Huevo entero fresco', 44, 2),
('Modelo SMC 015', 'Brócoli cocido', 92, 3),
('Modelo SMC 015', 'Aceite', 10, 4),
('Modelo SMC 016', 'Arroz cocido', 75, 1),
('Modelo SMC 016', 'Huevo entero fresco', 44, 2),
('Modelo SMC 016', 'Brócoli cocido', 92, 3),
('Modelo SMC 016', 'Aceite de oliva', 10, 4),
('Modelo SMC 017', 'Arroz cocido', 75, 1),
('Modelo SMC 017', 'Huevo entero fresco', 44, 2),
('Modelo SMC 017', 'Brócoli cocido', 92, 3),
('Modelo SMC 017', 'Aguacate hass', 58, 4),
('Modelo SMC 018', 'Arroz cocido', 75, 1),
('Modelo SMC 018', 'Huevo entero fresco', 44, 2),
('Modelo SMC 018', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 018', 'Aceite', 10, 4),
('Modelo SMC 019', 'Arroz cocido', 75, 1),
('Modelo SMC 019', 'Huevo entero fresco', 44, 2),
('Modelo SMC 019', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 019', 'Aceite de oliva', 10, 4),
('Modelo SMC 020', 'Arroz cocido', 75, 1),
('Modelo SMC 020', 'Huevo entero fresco', 44, 2),
('Modelo SMC 020', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 020', 'Aguacate hass', 58, 4),
('Modelo SMC 021', 'Arroz cocido', 75, 1),
('Modelo SMC 021', 'Huevo entero fresco', 44, 2),
('Modelo SMC 021', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 021', 'Aceite', 10, 4),
('Modelo SMC 022', 'Arroz cocido', 75, 1),
('Modelo SMC 022', 'Huevo entero fresco', 44, 2),
('Modelo SMC 022', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 022', 'Aceite de oliva', 10, 4),
('Modelo SMC 023', 'Arroz cocido', 75, 1),
('Modelo SMC 023', 'Huevo entero fresco', 44, 2),
('Modelo SMC 023', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 023', 'Aguacate hass', 58, 4),
('Modelo SMC 024', 'Arroz cocido', 75, 1),
('Modelo SMC 024', 'Huevo entero fresco', 44, 2),
('Modelo SMC 024', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 024', 'Aceite', 10, 4),
('Modelo SMC 025', 'Arroz cocido', 75, 1),
('Modelo SMC 025', 'Huevo entero fresco', 44, 2),
('Modelo SMC 025', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 025', 'Aceite de oliva', 10, 4),
('Modelo SMC 026', 'Arroz cocido', 75, 1),
('Modelo SMC 026', 'Huevo entero fresco', 44, 2),
('Modelo SMC 026', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 026', 'Aguacate hass', 58, 4),
('Modelo SMC 027', 'Arroz cocido', 75, 1),
('Modelo SMC 027', 'Huevo entero fresco', 44, 2),
('Modelo SMC 027', 'Espárragos crudos', 90, 3),
('Modelo SMC 027', 'Aceite', 10, 4),
('Modelo SMC 028', 'Arroz cocido', 75, 1),
('Modelo SMC 028', 'Huevo entero fresco', 44, 2),
('Modelo SMC 028', 'Espárragos crudos', 90, 3),
('Modelo SMC 028', 'Aceite de oliva', 10, 4),
('Modelo SMC 029', 'Arroz cocido', 75, 1),
('Modelo SMC 029', 'Huevo entero fresco', 44, 2),
('Modelo SMC 029', 'Espárragos crudos', 90, 3),
('Modelo SMC 029', 'Aguacate hass', 58, 4),
('Modelo SMC 030', 'Arroz cocido', 75, 1),
('Modelo SMC 030', 'Huevo entero fresco', 44, 2),
('Modelo SMC 030', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 030', 'Aceite', 10, 4),
('Modelo SMC 031', 'Arroz cocido', 75, 1),
('Modelo SMC 031', 'Huevo entero fresco', 44, 2),
('Modelo SMC 031', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 031', 'Aceite de oliva', 10, 4),
('Modelo SMC 032', 'Arroz cocido', 75, 1),
('Modelo SMC 032', 'Huevo entero fresco', 44, 2),
('Modelo SMC 032', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 032', 'Aguacate hass', 58, 4),
('Modelo SMC 033', 'Arroz cocido', 75, 1),
('Modelo SMC 033', 'Huevo entero cocido', 44, 2),
('Modelo SMC 033', 'Jitomate', 113, 3),
('Modelo SMC 033', 'Aceite', 10, 4),
('Modelo SMC 034', 'Arroz cocido', 75, 1),
('Modelo SMC 034', 'Huevo entero cocido', 44, 2),
('Modelo SMC 034', 'Jitomate', 113, 3),
('Modelo SMC 034', 'Aceite de oliva', 10, 4),
('Modelo SMC 035', 'Arroz cocido', 75, 1),
('Modelo SMC 035', 'Huevo entero cocido', 44, 2),
('Modelo SMC 035', 'Jitomate', 113, 3),
('Modelo SMC 035', 'Aguacate hass', 58, 4),
('Modelo SMC 036', 'Arroz cocido', 75, 1),
('Modelo SMC 036', 'Huevo entero cocido', 44, 2),
('Modelo SMC 036', 'Lechuga', 135, 3),
('Modelo SMC 036', 'Aceite', 10, 4),
('Modelo SMC 037', 'Arroz cocido', 75, 1),
('Modelo SMC 037', 'Huevo entero cocido', 44, 2),
('Modelo SMC 037', 'Lechuga', 135, 3),
('Modelo SMC 037', 'Aceite de oliva', 10, 4),
('Modelo SMC 038', 'Arroz cocido', 75, 1),
('Modelo SMC 038', 'Huevo entero cocido', 44, 2),
('Modelo SMC 038', 'Lechuga', 135, 3),
('Modelo SMC 038', 'Aguacate hass', 58, 4),
('Modelo SMC 039', 'Arroz cocido', 75, 1),
('Modelo SMC 039', 'Huevo entero cocido', 44, 2),
('Modelo SMC 039', 'Brócoli cocido', 92, 3),
('Modelo SMC 039', 'Aceite', 10, 4),
('Modelo SMC 040', 'Arroz cocido', 75, 1),
('Modelo SMC 040', 'Huevo entero cocido', 44, 2),
('Modelo SMC 040', 'Brócoli cocido', 92, 3),
('Modelo SMC 040', 'Aceite de oliva', 10, 4),
('Modelo SMC 041', 'Arroz cocido', 75, 1),
('Modelo SMC 041', 'Huevo entero cocido', 44, 2),
('Modelo SMC 041', 'Brócoli cocido', 92, 3),
('Modelo SMC 041', 'Aguacate hass', 58, 4),
('Modelo SMC 042', 'Arroz cocido', 75, 1),
('Modelo SMC 042', 'Huevo entero cocido', 44, 2),
('Modelo SMC 042', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 042', 'Aceite', 10, 4),
('Modelo SMC 043', 'Arroz cocido', 75, 1),
('Modelo SMC 043', 'Huevo entero cocido', 44, 2),
('Modelo SMC 043', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 043', 'Aceite de oliva', 10, 4),
('Modelo SMC 044', 'Arroz cocido', 75, 1),
('Modelo SMC 044', 'Huevo entero cocido', 44, 2),
('Modelo SMC 044', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 044', 'Aguacate hass', 58, 4),
('Modelo SMC 045', 'Arroz cocido', 75, 1),
('Modelo SMC 045', 'Huevo entero cocido', 44, 2),
('Modelo SMC 045', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 045', 'Aceite', 10, 4),
('Modelo SMC 046', 'Arroz cocido', 75, 1),
('Modelo SMC 046', 'Huevo entero cocido', 44, 2),
('Modelo SMC 046', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 046', 'Aceite de oliva', 10, 4),
('Modelo SMC 047', 'Arroz cocido', 75, 1),
('Modelo SMC 047', 'Huevo entero cocido', 44, 2),
('Modelo SMC 047', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 047', 'Aguacate hass', 58, 4),
('Modelo SMC 048', 'Arroz cocido', 75, 1),
('Modelo SMC 048', 'Huevo entero cocido', 44, 2),
('Modelo SMC 048', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 048', 'Aceite', 10, 4),
('Modelo SMC 049', 'Arroz cocido', 75, 1),
('Modelo SMC 049', 'Huevo entero cocido', 44, 2),
('Modelo SMC 049', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 049', 'Aceite de oliva', 10, 4),
('Modelo SMC 050', 'Arroz cocido', 75, 1),
('Modelo SMC 050', 'Huevo entero cocido', 44, 2),
('Modelo SMC 050', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 050', 'Aguacate hass', 58, 4),
('Modelo SMC 051', 'Arroz cocido', 75, 1),
('Modelo SMC 051', 'Huevo entero cocido', 44, 2),
('Modelo SMC 051', 'Espárragos crudos', 90, 3),
('Modelo SMC 051', 'Aceite', 10, 4),
('Modelo SMC 052', 'Arroz cocido', 75, 1),
('Modelo SMC 052', 'Huevo entero cocido', 44, 2),
('Modelo SMC 052', 'Espárragos crudos', 90, 3),
('Modelo SMC 052', 'Aceite de oliva', 10, 4),
('Modelo SMC 053', 'Arroz cocido', 75, 1),
('Modelo SMC 053', 'Huevo entero cocido', 44, 2),
('Modelo SMC 053', 'Espárragos crudos', 90, 3),
('Modelo SMC 053', 'Aguacate hass', 58, 4),
('Modelo SMC 054', 'Arroz cocido', 75, 1),
('Modelo SMC 054', 'Huevo entero cocido', 44, 2),
('Modelo SMC 054', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 054', 'Aceite', 10, 4),
('Modelo SMC 055', 'Arroz cocido', 75, 1),
('Modelo SMC 055', 'Huevo entero cocido', 44, 2),
('Modelo SMC 055', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 055', 'Aceite de oliva', 10, 4),
('Modelo SMC 056', 'Arroz cocido', 75, 1),
('Modelo SMC 056', 'Huevo entero cocido', 44, 2),
('Modelo SMC 056', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 056', 'Aguacate hass', 58, 4),
('Modelo SMC 057', 'Arroz cocido', 75, 1),
('Modelo SMC 057', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 057', 'Jitomate', 113, 3),
('Modelo SMC 057', 'Aceite', 10, 4),
('Modelo SMC 058', 'Arroz cocido', 75, 1),
('Modelo SMC 058', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 058', 'Jitomate', 113, 3),
('Modelo SMC 058', 'Aceite de oliva', 10, 4),
('Modelo SMC 059', 'Arroz cocido', 75, 1),
('Modelo SMC 059', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 059', 'Jitomate', 113, 3),
('Modelo SMC 059', 'Aguacate hass', 58, 4),
('Modelo SMC 060', 'Arroz cocido', 75, 1),
('Modelo SMC 060', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 060', 'Lechuga', 135, 3),
('Modelo SMC 060', 'Aceite', 10, 4),
('Modelo SMC 061', 'Arroz cocido', 75, 1),
('Modelo SMC 061', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 061', 'Lechuga', 135, 3),
('Modelo SMC 061', 'Aceite de oliva', 10, 4),
('Modelo SMC 062', 'Arroz cocido', 75, 1),
('Modelo SMC 062', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 062', 'Lechuga', 135, 3),
('Modelo SMC 062', 'Aguacate hass', 58, 4),
('Modelo SMC 063', 'Arroz cocido', 75, 1),
('Modelo SMC 063', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 063', 'Brócoli cocido', 92, 3),
('Modelo SMC 063', 'Aceite', 10, 4),
('Modelo SMC 064', 'Arroz cocido', 75, 1),
('Modelo SMC 064', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 064', 'Brócoli cocido', 92, 3),
('Modelo SMC 064', 'Aceite de oliva', 10, 4),
('Modelo SMC 065', 'Arroz cocido', 75, 1),
('Modelo SMC 065', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 065', 'Brócoli cocido', 92, 3),
('Modelo SMC 065', 'Aguacate hass', 58, 4),
('Modelo SMC 066', 'Arroz cocido', 75, 1),
('Modelo SMC 066', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 066', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 066', 'Aceite', 10, 4),
('Modelo SMC 067', 'Arroz cocido', 75, 1),
('Modelo SMC 067', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 067', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 067', 'Aceite de oliva', 10, 4),
('Modelo SMC 068', 'Arroz cocido', 75, 1),
('Modelo SMC 068', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 068', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 068', 'Aguacate hass', 58, 4),
('Modelo SMC 069', 'Arroz cocido', 75, 1),
('Modelo SMC 069', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 069', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 069', 'Aceite', 10, 4),
('Modelo SMC 070', 'Arroz cocido', 75, 1),
('Modelo SMC 070', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 070', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 070', 'Aceite de oliva', 10, 4),
('Modelo SMC 071', 'Arroz cocido', 75, 1),
('Modelo SMC 071', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 071', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 071', 'Aguacate hass', 58, 4),
('Modelo SMC 072', 'Arroz cocido', 75, 1),
('Modelo SMC 072', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 072', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 072', 'Aceite', 10, 4),
('Modelo SMC 073', 'Arroz cocido', 75, 1),
('Modelo SMC 073', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 073', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 073', 'Aceite de oliva', 10, 4),
('Modelo SMC 074', 'Arroz cocido', 75, 1),
('Modelo SMC 074', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 074', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 074', 'Aguacate hass', 58, 4),
('Modelo SMC 075', 'Arroz cocido', 75, 1),
('Modelo SMC 075', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 075', 'Espárragos crudos', 90, 3),
('Modelo SMC 075', 'Aceite', 10, 4),
('Modelo SMC 076', 'Arroz cocido', 75, 1),
('Modelo SMC 076', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 076', 'Espárragos crudos', 90, 3),
('Modelo SMC 076', 'Aceite de oliva', 10, 4),
('Modelo SMC 077', 'Arroz cocido', 75, 1),
('Modelo SMC 077', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 077', 'Espárragos crudos', 90, 3),
('Modelo SMC 077', 'Aguacate hass', 58, 4),
('Modelo SMC 078', 'Arroz cocido', 75, 1),
('Modelo SMC 078', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 078', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 078', 'Aceite', 10, 4),
('Modelo SMC 079', 'Arroz cocido', 75, 1),
('Modelo SMC 079', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 079', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 079', 'Aceite de oliva', 10, 4),
('Modelo SMC 080', 'Arroz cocido', 75, 1),
('Modelo SMC 080', 'Pollo sin piel cocido', 30, 2),
('Modelo SMC 080', 'Champiñon cocido entero', 78, 3),
('Modelo SMC 080', 'Aguacate hass', 58, 4),
('Modelo SMC 081', 'Arroz cocido', 75, 1),
('Modelo SMC 081', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 081', 'Jitomate', 113, 3),
('Modelo SMC 081', 'Aceite', 10, 4),
('Modelo SMC 082', 'Arroz cocido', 75, 1),
('Modelo SMC 082', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 082', 'Jitomate', 113, 3),
('Modelo SMC 082', 'Aceite de oliva', 10, 4),
('Modelo SMC 083', 'Arroz cocido', 75, 1),
('Modelo SMC 083', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 083', 'Jitomate', 113, 3),
('Modelo SMC 083', 'Aguacate hass', 58, 4),
('Modelo SMC 084', 'Arroz cocido', 75, 1),
('Modelo SMC 084', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 084', 'Lechuga', 135, 3),
('Modelo SMC 084', 'Aceite', 10, 4),
('Modelo SMC 085', 'Arroz cocido', 75, 1),
('Modelo SMC 085', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 085', 'Lechuga', 135, 3),
('Modelo SMC 085', 'Aceite de oliva', 10, 4),
('Modelo SMC 086', 'Arroz cocido', 75, 1),
('Modelo SMC 086', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 086', 'Lechuga', 135, 3),
('Modelo SMC 086', 'Aguacate hass', 58, 4),
('Modelo SMC 087', 'Arroz cocido', 75, 1),
('Modelo SMC 087', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 087', 'Brócoli cocido', 92, 3),
('Modelo SMC 087', 'Aceite', 10, 4),
('Modelo SMC 088', 'Arroz cocido', 75, 1),
('Modelo SMC 088', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 088', 'Brócoli cocido', 92, 3),
('Modelo SMC 088', 'Aceite de oliva', 10, 4),
('Modelo SMC 089', 'Arroz cocido', 75, 1),
('Modelo SMC 089', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 089', 'Brócoli cocido', 92, 3),
('Modelo SMC 089', 'Aguacate hass', 58, 4),
('Modelo SMC 090', 'Arroz cocido', 75, 1),
('Modelo SMC 090', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 090', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 090', 'Aceite', 10, 4),
('Modelo SMC 091', 'Arroz cocido', 75, 1),
('Modelo SMC 091', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 091', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 091', 'Aceite de oliva', 10, 4),
('Modelo SMC 092', 'Arroz cocido', 75, 1),
('Modelo SMC 092', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 092', 'Pepino con cáscara rebanado', 104, 3),
('Modelo SMC 092', 'Aguacate hass', 58, 4),
('Modelo SMC 093', 'Arroz cocido', 75, 1),
('Modelo SMC 093', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 093', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 093', 'Aceite', 10, 4),
('Modelo SMC 094', 'Arroz cocido', 75, 1),
('Modelo SMC 094', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 094', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 094', 'Aceite de oliva', 10, 4),
('Modelo SMC 095', 'Arroz cocido', 75, 1),
('Modelo SMC 095', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 095', 'Calabacita alargada cruda', 91, 3),
('Modelo SMC 095', 'Aguacate hass', 58, 4),
('Modelo SMC 096', 'Arroz cocido', 75, 1),
('Modelo SMC 096', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 096', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 096', 'Aceite', 10, 4),
('Modelo SMC 097', 'Arroz cocido', 75, 1),
('Modelo SMC 097', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 097', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 097', 'Aceite de oliva', 10, 4),
('Modelo SMC 098', 'Arroz cocido', 75, 1),
('Modelo SMC 098', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 098', 'Ejotes cocidos picados', 63, 3),
('Modelo SMC 098', 'Aguacate hass', 58, 4),
('Modelo SMC 099', 'Arroz cocido', 75, 1),
('Modelo SMC 099', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 099', 'Espárragos crudos', 90, 3),
('Modelo SMC 099', 'Aceite', 10, 4),
('Modelo SMC 100', 'Arroz cocido', 75, 1),
('Modelo SMC 100', 'Pollo crudo sin piel', 26, 2),
('Modelo SMC 100', 'Espárragos crudos', 90, 3),
('Modelo SMC 100', 'Aceite de oliva', 10, 4);