-- Tables missing from Hibernate H2 SCRIPT export (Paciente @Delegate satellites). Issue #46.

CREATE TABLE IF NOT EXISTS paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bmr REAL,
    dob DATE NOT NULL,
    email VARCHAR(100),
    estatura REAL,
    gender VARCHAR(1) NOT NULL,
    imc REAL,
    name VARCHAR(100) NOT NULL,
    nivel_peso SMALLINT,
    parentesco VARCHAR(255),
    peso REAL,
    phone VARCHAR(25),
    pregnancy BOOLEAN,
    registro TIMESTAMP(6),
    responsible_name VARCHAR(100),
    user_id VARCHAR(255) NOT NULL,
    patient_auth_sub VARCHAR(255),
    get_kcal REAL,
    tef_kcal REAL,
    total_adjusted_kcal REAL,
    final_total_kcal REAL,
    stress_kcal REAL
);

CREATE TABLE IF NOT EXISTS paciente_dieta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    end_date DATE,
    notes CLOB,
    start_date DATE NOT NULL,
    status SMALLINT NOT NULL,
    dieta_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS calendar_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description CLOB,
    diastolica INTEGER,
    duration_minutes INTEGER NOT NULL,
    estatura REAL,
    event_date_time TIMESTAMP(6) NOT NULL,
    imc REAL,
    indice_glucemico INTEGER,
    indice_grasa_corporal REAL,
    nivel_peso SMALLINT,
    peso REAL,
    pulso INTEGER,
    sistolica INTEGER,
    spo2 REAL,
    status SMALLINT NOT NULL,
    summary_notes CLOB,
    temperatura REAL,
    title VARCHAR(200) NOT NULL,
    paciente_id BIGINT NOT NULL,
    activity_factor REAL,
    bmr_formula VARCHAR(30),
    bmr_used REAL,
    get_kcal REAL,
    physical_activity_level VARCHAR(30),
    tef_kcal REAL,
    total_adjusted_kcal REAL,
    final_total_kcal REAL,
    physiological_stress_active BOOLEAN,
    physiological_stress_type VARCHAR(40),
    stress_factor_value REAL,
    stress_fever_temperature REAL,
    stress_formula_table VARCHAR(30),
    stress_increment_mode VARCHAR(30),
    stress_kcal REAL,
    stress_valid_from DATE,
    stress_valid_until DATE
);

CREATE TABLE IF NOT EXISTS body_mass (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_mass_value REAL,
    height REAL,
    imc REAL,
    nivel_peso SMALLINT,
    weight REAL
);

CREATE TABLE IF NOT EXISTS vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diastolica INTEGER,
    estatura REAL,
    imc REAL,
    indice_glucemico INTEGER,
    nivel_peso SMALLINT,
    peso REAL,
    pulso INTEGER,
    sistolica INTEGER,
    spo2 REAL,
    temperatura REAL
);

CREATE TABLE IF NOT EXISTS seed_platillo (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    description VARCHAR(510),
    ingestas_sugeridas VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS seed_platillo_ingrediente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platillo_name VARCHAR(255) NOT NULL,
    alimento_nombre VARCHAR(255) NOT NULL,
    alimento_id BIGINT,
    peso_neto INTEGER NOT NULL,
    orden INTEGER DEFAULT 1 NOT NULL
);
