CREATE SCHEMA IF NOT EXISTS public;
SET SCHEMA public;

CREATE TABLE spring_session(
    primary_id CHARACTER(36) NOT NULL,
    session_id CHARACTER(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INTEGER NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name CHARACTER VARYING(100)
);  
ALTER TABLE spring_session ADD CONSTRAINT spring_session_pk PRIMARY KEY(primary_id);   
CREATE UNIQUE NULLS DISTINCT INDEX spring_session_ix1 ON spring_session(session_id NULLS LAST);        
CREATE INDEX spring_session_ix2 ON spring_session(expiry_time NULLS LAST);             
CREATE INDEX spring_session_ix3 ON spring_session(principal_name NULLS LAST);          
CREATE TABLE spring_session_attributes(
    session_primary_id CHARACTER(36) NOT NULL,
    attribute_name CHARACTER VARYING(200) NOT NULL,
    attribute_bytes BINARY VARYING NOT NULL
);              
ALTER TABLE spring_session_attributes ADD CONSTRAINT spring_session_attributes_pk PRIMARY KEY(session_primary_id, attribute_name);   
CREATE TABLE alimento(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    cant_sugerida FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    clasificacion CHARACTER VARYING(255) NOT NULL,
    nombre_alimento CHARACTER VARYING(255) NOT NULL,
    unidad CHARACTER VARYING(255)
);             
ALTER TABLE alimento ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY(id);      
CREATE TABLE alimento_ingesta(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    portions INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    alimento_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    ingesta_id BIGINT,
    name CHARACTER VARYING(255),
    unidad CHARACTER VARYING(255)
);  
ALTER TABLE alimento_ingesta ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY(id);              
CREATE TABLE anthropometric_measurement(
    activity_factor FLOAT(14),
    bmr_used FLOAT(24),
    final_total_kcal FLOAT(24),
    get_kcal FLOAT(24),
    physiological_stress_active BOOLEAN,
    stress_factor_value FLOAT(17),
    stress_fever_temperature FLOAT(14),
    stress_kcal FLOAT(24),
    stress_valid_from DATE,
    stress_valid_until DATE,
    tef_kcal FLOAT(24),
    total_adjusted_kcal FLOAT(24),
    bioimpedance_id BIGINT,
    body_composition_id BIGINT,
    body_mass_id BIGINT,
    circumferences_id BIGINT,
    diameters_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    measurement_date_time TIMESTAMP(6) NOT NULL,
    paciente_id BIGINT NOT NULL,
    skinfolds_id BIGINT,
    title CHARACTER VARYING(200) NOT NULL,
    description CHARACTER VARYING,
    notes CHARACTER VARYING,
    bmr_formula ENUM('FAO_WHO_ONU', 'HARRIS_BENEDICT', 'MIFFLIN_ST_JEOR', 'PROMEDIO', 'VALENCIA'),
    physical_activity_level ENUM('CUSTOM', 'INTENSE', 'LIGHT', 'MODERATE', 'SEDENTARY', 'VERY_INTENSE'),
    physiological_stress_type ENUM('BURNS', 'CANCER', 'COPD_EXACERBATION', 'FEVER', 'FRACTURE', 'HEAD_INJURY', 'MAJOR_SURGERY', 'MINOR_SURGERY', 'MODERATE_INFECTION', 'MULTIPLE_TRAUMA', 'NONE', 'ORGAN_FAILURE', 'OTHER', 'POST_OPERATIVE', 'PREGNANCY_COMPLICATION', 'SEPSIS', 'SEVERE_INFECTION', 'TRAUMA'),
    stress_formula_table ENUM('ASPEN', 'CUSTOM', 'FEVER_PER_DEGREE', 'LONG'),
    stress_increment_mode ENUM('FIXED_KCAL', 'MULTIPLIER_BMR', 'MULTIPLIER_GET')
); 
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4F4764 PRIMARY KEY(id);              
CREATE TABLE bioimpedance(
    bioimpedance_value FLOAT(17),
    body_fat_percentage FLOAT(10),
    bone_mass FLOAT(17),
    bone_mass_percentage FLOAT(10),
    ecw_icw_ratio FLOAT(10),
    estimated_basal_metabolism FLOAT(17),
    extracellular_water FLOAT(17),
    fat_free_mass FLOAT(17),
    fat_mass FLOAT(17),
    impedance FLOAT(17),
    intracellular_water FLOAT(17),
    phase_angle FLOAT(10),
    reactance FLOAT(17),
    resistance FLOAT(17),
    skeletal_muscle_mass FLOAT(17),
    total_body_water_liters FLOAT(17),
    total_body_water_percentage FLOAT(10),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);     
ALTER TABLE bioimpedance ADD CONSTRAINT CONSTRAINT_D PRIMARY KEY(id);  
CREATE TABLE blood_chemistry(
    bun FLOAT(17),
    creatinina FLOAT(17),
    glucosa FLOAT(17),
    hba1c FLOAT(17),
    urea FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);              
ALTER TABLE blood_chemistry ADD CONSTRAINT CONSTRAINT_69 PRIMARY KEY(id);              
CREATE TABLE body_metric_record(
    bmr FLOAT(24),
    body_fat_index FLOAT(10),
    body_fat_percentage FLOAT(10),
    get_kcal FLOAT(24),
    height FLOAT(10),
    imc FLOAT(10),
    tef_kcal FLOAT(24),
    total_adjusted_kcal FLOAT(24),
    weight FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    paciente_id BIGINT NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL,
    source_id BIGINT NOT NULL,
    metodo_obtencion_composicion ENUM('BIOIMPEDANCIA', 'DEURENBERG', 'DEXA', 'MANUAL', 'OTRO', 'PLIEGUES'),
    nivel_peso ENUM('ALTO', 'BAJO', 'NORMAL', 'SOBREPESO'),
    source ENUM('ANTHROPOMETRIC', 'CLINICAL_EXAM', 'CONSULTATION') NOT NULL
);  
ALTER TABLE body_metric_record ADD CONSTRAINT CONSTRAINT_DD PRIMARY KEY(id);           
CREATE INDEX idx_body_metric_paciente_date ON body_metric_record(paciente_id NULLS LAST, recorded_at NULLS LAST);    
CREATE TABLE body_composition(
    ectomorphy FLOAT(14),
    endomorphy FLOAT(14),
    indice_grasa_corporal FLOAT(10),
    masa_osea_kg FLOAT(17),
    mesomorphy FLOAT(14),
    porcentaje_grasa_corporal FLOAT(10),
    porcentaje_masa_muscular FLOAT(10),
    porcentaje_masa_osea FLOAT(10),
    somatocartax FLOAT(14),
    somatocartay FLOAT(14),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    metodo_obtencion ENUM('BIOIMPEDANCIA', 'DEURENBERG', 'DEXA', 'MANUAL', 'OTRO', 'PLIEGUES')
);  
ALTER TABLE body_composition ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(id);              
CREATE TABLE circumferences(
    ankle_circumference FLOAT(17),
    calf_circumference FLOAT(17),
    cephalic_circumference FLOAT(17),
    forearm_circumference FLOAT(17),
    hip_circumference FLOAT(17),
    mesosternal_circumference FLOAT(17),
    mid_thigh_circumference FLOAT(17),
    mid_upper_arm_circumference_contracted FLOAT(17),
    mid_upper_arm_circumference_relaxed FLOAT(17),
    neck_circumference FLOAT(17),
    thigh_circumference FLOAT(17),
    umbilical_circumference FLOAT(17),
    waist_circumference FLOAT(17),
    wrist_circumference FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);              
ALTER TABLE circumferences ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY(id);
CREATE TABLE clinical_exam(
    blood_chemistry_id BIGINT,
    body_composition_id BIGINT,
    complete_blood_count_id BIGINT,
    exam_date_time TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    lipid_profile_id BIGINT,
    liver_function_id BIGINT,
    other_tests_id BIGINT,
    paciente_id BIGINT NOT NULL,
    vital_signs_id BIGINT,
    title CHARACTER VARYING(200) NOT NULL,
    description CHARACTER VARYING,
    summary_notes CHARACTER VARYING
);             
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A115DCB PRIMARY KEY(id);          
CREATE TABLE complete_blood_count(
    hematocrito FLOAT(17),
    hemoglobina FLOAT(17),
    leucocitos FLOAT(17),
    plaquetas FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);               
ALTER TABLE complete_blood_count ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY(id);          
CREATE TABLE contact_inquiry(
    read_by_admin BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name CHARACTER VARYING(100) NOT NULL,
    subject CHARACTER VARYING(200) NOT NULL,
    message CHARACTER VARYING(2000) NOT NULL,
    email CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE contact_inquiry ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY(id);               
CREATE TABLE diameters(
    anteroposterior_thorax_diameter FLOAT(17),
    biacromial_diameter FLOAT(17),
    biestiloid_wrist_diameter FLOAT(17),
    biiliocrestal_diameter FLOAT(17),
    bimaleolar_diameter FLOAT(17),
    femur_diameter FLOAT(17),
    foot_length FLOAT(17),
    hand_length FLOAT(17),
    humerus_diameter FLOAT(17),
    transverse_foot_diameter FLOAT(17),
    transverse_hand_diameter FLOAT(17),
    transverse_thorax_diameter FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
); 
ALTER TABLE diameters ADD CONSTRAINT CONSTRAINT_51 PRIMARY KEY(id);    
CREATE TABLE dieta(
    energia INTEGER,
    hidratos_de_carbono FLOAT(17),
    lipidos FLOAT(17),
    proteina FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    nombre CHARACTER VARYING(255),
    user_id CHARACTER VARYING(255) NOT NULL
);            
ALTER TABLE dieta ADD CONSTRAINT CONSTRAINT_5B PRIMARY KEY(id);        
CREATE TABLE ingesta(
    energia INTEGER,
    hidratos_de_carbono FLOAT(17),
    lipidos FLOAT(17),
    proteina FLOAT(17),
    dieta_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    nombre CHARACTER VARYING(255)
);  
ALTER TABLE ingesta ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY(id);       
CREATE TABLE ingrediente(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    cant_sugerida FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    alimento_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    platillo_id BIGINT NOT NULL,
    description CHARACTER VARYING(255),
    unidad CHARACTER VARYING(255)
);               
ALTER TABLE ingrediente ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY(id);   
CREATE TABLE ingrediente_platillo_ingesta(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    cant_sugerida FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    alimento_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    platillo_id BIGINT NOT NULL,
    description CHARACTER VARYING(255),
    unidad CHARACTER VARYING(255)
);              
ALTER TABLE ingrediente_platillo_ingesta ADD CONSTRAINT CONSTRAINT_57 PRIMARY KEY(id); 
CREATE TABLE lipid_profile(
    colesterol_total FLOAT(17),
    hdl FLOAT(17),
    ldl FLOAT(17),
    trigliceridos FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);            
ALTER TABLE lipid_profile ADD CONSTRAINT CONSTRAINT_82 PRIMARY KEY(id);
CREATE TABLE liver_function(
    alt FLOAT(17),
    ast FLOAT(17),
    bilirrubina FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);               
ALTER TABLE liver_function ADD CONSTRAINT CONSTRAINT_87 PRIMARY KEY(id);               
CREATE TABLE nutritionist_profile(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    registro TIMESTAMP(6) NOT NULL,
    logo_extension CHARACTER VARYING(10),
    cedula_profesional CHARACTER VARYING(20),
    display_name CHARACTER VARYING(100),
    user_id CHARACTER VARYING(255) NOT NULL
);    
ALTER TABLE nutritionist_profile ADD CONSTRAINT CONSTRAINT_957 PRIMARY KEY(id);        
CREATE TABLE other_indicators(
    ferritina FLOAT(17),
    hierro FLOAT(17),
    vitaminab12 FLOAT(17),
    vitaminad FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);         
ALTER TABLE other_indicators ADD CONSTRAINT CONSTRAINT_EB PRIMARY KEY(id);             
CREATE TABLE paciente_energy_preferences(
    activity_factor FLOAT(14),
    custom_factor_intense FLOAT(14),
    custom_factor_light FLOAT(14),
    custom_factor_moderate FLOAT(14),
    custom_factor_sedentary FLOAT(14),
    custom_factor_very_intense FLOAT(14),
    physiological_stress_active BOOLEAN,
    stress_factor_value FLOAT(17),
    stress_fever_temperature FLOAT(14),
    stress_valid_from DATE,
    stress_valid_until DATE,
    tef_fixed_percent FLOAT(17),
    tef_macro_carbs_percent FLOAT(17),
    tef_macro_fat_percent FLOAT(17),
    tef_macro_protein_percent FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    paciente_id BIGINT NOT NULL,
    activity_factor_scale ENUM('CUSTOM', 'FAO_WHO', 'HARRIS_BENEDICT', 'OMS'),
    physical_activity_level ENUM('CUSTOM', 'INTENSE', 'LIGHT', 'MODERATE', 'SEDENTARY', 'VERY_INTENSE'),
    physiological_stress_type ENUM('BURNS', 'CANCER', 'COPD_EXACERBATION', 'FEVER', 'FRACTURE', 'HEAD_INJURY', 'MAJOR_SURGERY', 'MINOR_SURGERY', 'MODERATE_INFECTION', 'MULTIPLE_TRAUMA', 'NONE', 'ORGAN_FAILURE', 'OTHER', 'POST_OPERATIVE', 'PREGNANCY_COMPLICATION', 'SEPSIS', 'SEVERE_INFECTION', 'TRAUMA'),
    preferred_bmr_formula ENUM('FAO_WHO_ONU', 'HARRIS_BENEDICT', 'MIFFLIN_ST_JEOR', 'PROMEDIO', 'VALENCIA'),
    stress_formula_table ENUM('ASPEN', 'CUSTOM', 'FEVER_PER_DEGREE', 'LONG'),
    stress_increment_mode ENUM('FIXED_KCAL', 'MULTIPLIER_BMR', 'MULTIPLIER_GET'),
    tef_base ENUM('BMR', 'GET'),
    tef_method ENUM('FIXED', 'MACRONUTRIENTS')
);
ALTER TABLE paciente_energy_preferences ADD CONSTRAINT CONSTRAINT_E60 PRIMARY KEY(id); 
CREATE TABLE paciente_medical_history(
    anemia BOOLEAN,
    anorexia BOOLEAN,
    bulimia BOOLEAN,
    diabetes BOOLEAN,
    enfermedades_hepaticas BOOLEAN,
    hipertension BOOLEAN,
    hipotiroidismo BOOLEAN,
    obesidad BOOLEAN,
    tipo_sanguineo CHARACTER VARYING(4),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    paciente_id BIGINT NOT NULL,
    alergias CHARACTER VARYING,
    antecedentes_natales CHARACTER VARYING,
    antecedentes_patologicos_familiares CHARACTER VARYING,
    antecedentes_patologicos_personales CHARACTER VARYING,
    antecedentes_prenatales CHARACTER VARYING,
    complicaciones CHARACTER VARYING,
    desarrollo_psicomotor CHARACTER VARYING,
    historial_alimenticio CHARACTER VARYING
);        
ALTER TABLE paciente_medical_history ADD CONSTRAINT CONSTRAINT_11 PRIMARY KEY(id);     
CREATE TABLE patient_message(
    read_by_nutritionist BOOLEAN NOT NULL,
    read_by_patient BOOLEAN NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    paciente_id BIGINT NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    body CHARACTER VARYING(2000) NOT NULL,
    nutritionist_user_id CHARACTER VARYING(255) NOT NULL,
    sender_role ENUM('NUTRITIONIST', 'PATIENT') NOT NULL
);    
ALTER TABLE patient_message ADD CONSTRAINT CONSTRAINT_CA PRIMARY KEY(id);              
CREATE TABLE platillo(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    description CHARACTER VARYING(255),
    image_url CHARACTER VARYING(255),
    ingestas_sugeridas CHARACTER VARYING(255),
    name CHARACTER VARYING(255),
    pdf_url CHARACTER VARYING(255),
    video_url CHARACTER VARYING(255)
);         
ALTER TABLE platillo ADD CONSTRAINT CONSTRAINT_6F PRIMARY KEY(id);     
CREATE TABLE platillo_ingesta(
    acido_ascorbico FLOAT(17),
    acido_folico FLOAT(17),
    ag_monoinsaturados FLOAT(17),
    ag_poliinsaturados FLOAT(17),
    ag_saturados FLOAT(17),
    azucar_por_equivalente FLOAT(17),
    calcio FLOAT(17),
    carga_glicemica FLOAT(17),
    colesterol FLOAT(17),
    energia INTEGER,
    etanol FLOAT(17),
    fibra FLOAT(17),
    fosforo FLOAT(17),
    hidratos_de_carbono FLOAT(17),
    hierro FLOAT(17),
    hierro_no_hem FLOAT(17),
    indice_glicemico FLOAT(17),
    lipidos FLOAT(17),
    peso_bruto_redondeado INTEGER,
    peso_neto INTEGER,
    portions INTEGER,
    potasio FLOAT(17),
    proteina FLOAT(17),
    selenio FLOAT(17),
    sodio FLOAT(17),
    vita FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    ingesta_id BIGINT,
    image_url CHARACTER VARYING(255),
    name CHARACTER VARYING(255),
    pdf_url CHARACTER VARYING(255),
    recommendations CHARACTER VARYING(255),
    video_url CHARACTER VARYING(255)
);             
ALTER TABLE platillo_ingesta ADD CONSTRAINT CONSTRAINT_92 PRIMARY KEY(id);             
CREATE TABLE skinfolds(
    abdominal_skinfold FLOAT(17),
    biceps_skinfold FLOAT(17),
    frontal_thigh_skinfold FLOAT(17),
    iliac_crest_skinfold FLOAT(17),
    medial_axillary_skinfold FLOAT(17),
    medial_calf_skinfold FLOAT(17),
    pectoral_skinfold FLOAT(17),
    subscapular_skinfold FLOAT(17),
    supraespinal_skinfold FLOAT(17),
    triceps_skinfold FLOAT(17),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL
);      
ALTER TABLE skinfolds ADD CONSTRAINT CONSTRAINT_79 PRIMARY KEY(id);    
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4F4 UNIQUE NULLS DISTINCT (circumferences_id);       
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A UNIQUE NULLS DISTINCT (body_composition_id);    
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4 UNIQUE NULLS DISTINCT (blood_chemistry_id);      
ALTER TABLE nutritionist_profile ADD CONSTRAINT CONSTRAINT_95 UNIQUE NULLS DISTINCT (user_id);         
ALTER TABLE paciente_medical_history ADD CONSTRAINT CONSTRAINT_1 UNIQUE NULLS DISTINCT (paciente_id);  
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A115DC UNIQUE NULLS DISTINCT (vital_signs_id);    
ALTER TABLE paciente_energy_preferences ADD CONSTRAINT CONSTRAINT_E6 UNIQUE NULLS DISTINCT (paciente_id);              
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A1 UNIQUE NULLS DISTINCT (complete_blood_count_id);               
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4F476 UNIQUE NULLS DISTINCT (skinfolds_id);          
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C UNIQUE NULLS DISTINCT (bioimpedance_id);            
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4F47 UNIQUE NULLS DISTINCT (diameters_id);           
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A115D UNIQUE NULLS DISTINCT (other_tests_id);     
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4F UNIQUE NULLS DISTINCT (body_mass_id);             
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A11 UNIQUE NULLS DISTINCT (lipid_profile_id);     
ALTER TABLE body_metric_record ADD CONSTRAINT uk_body_metric_source UNIQUE NULLS DISTINCT (source, source_id);       
ALTER TABLE anthropometric_measurement ADD CONSTRAINT CONSTRAINT_C4 UNIQUE NULLS DISTINCT (body_composition_id);       
ALTER TABLE clinical_exam ADD CONSTRAINT CONSTRAINT_4A115 UNIQUE NULLS DISTINCT (liver_function_id);   
ALTER TABLE ingrediente_platillo_ingesta ADD CONSTRAINT fk8wl4p7y8o17v9v018pfu0spsm FOREIGN KEY(platillo_id) REFERENCES platillo_ingesta(id) NOCHECK;     
ALTER TABLE clinical_exam ADD CONSTRAINT fkjfvoxbd2f2dgdveias0gvic90 FOREIGN KEY(blood_chemistry_id) REFERENCES blood_chemistry(id) NOCHECK;              
ALTER TABLE clinical_exam ADD CONSTRAINT fksfwdo95r563hhdih2vfwt056c FOREIGN KEY(complete_blood_count_id) REFERENCES complete_blood_count(id) NOCHECK;    
ALTER TABLE spring_session_attributes ADD CONSTRAINT spring_session_attributes_fk FOREIGN KEY(session_primary_id) REFERENCES spring_session(primary_id) ON DELETE CASCADE NOCHECK;        
ALTER TABLE clinical_exam ADD CONSTRAINT fk5f4r6a26tipmwt2tnwo3l8dwg FOREIGN KEY(body_composition_id) REFERENCES body_composition(id) NOCHECK;            
ALTER TABLE ingesta ADD CONSTRAINT fkjtyojiau15wr5cmu9cc8wsn26 FOREIGN KEY(dieta_id) REFERENCES dieta(id) NOCHECK;        
ALTER TABLE clinical_exam ADD CONSTRAINT fkp6ih6ousocjrju2ikqv1ya9rv FOREIGN KEY(other_tests_id) REFERENCES other_indicators(id) NOCHECK; 
ALTER TABLE ingrediente ADD CONSTRAINT fk8a4qhtoiupu5ypatjb4jhhaar FOREIGN KEY(platillo_id) REFERENCES platillo(id) NOCHECK;              
ALTER TABLE ingrediente ADD CONSTRAINT fknknqox49l28rbby5d80fynjmy FOREIGN KEY(alimento_id) REFERENCES alimento(id) NOCHECK;              
ALTER TABLE anthropometric_measurement ADD CONSTRAINT fksar6y6g775mycb6xtftkhjatf FOREIGN KEY(circumferences_id) REFERENCES circumferences(id) NOCHECK;   
ALTER TABLE anthropometric_measurement ADD CONSTRAINT fkqixumudvlkx188wvcjg4ri5fi FOREIGN KEY(bioimpedance_id) REFERENCES bioimpedance(id) NOCHECK;       
ALTER TABLE clinical_exam ADD CONSTRAINT fkmhoaojsdrjfwiax0h07qwluln FOREIGN KEY(lipid_profile_id) REFERENCES lipid_profile(id) NOCHECK;  
ALTER TABLE anthropometric_measurement ADD CONSTRAINT fkpw614ghhr0ci91jxfgc4xx2l6 FOREIGN KEY(diameters_id) REFERENCES diameters(id) NOCHECK;             
ALTER TABLE anthropometric_measurement ADD CONSTRAINT fkhuex07009t8bi872lgshasnan FOREIGN KEY(body_composition_id) REFERENCES body_composition(id) NOCHECK;               
ALTER TABLE ingrediente_platillo_ingesta ADD CONSTRAINT fk8l3062isqed3yp8rq1d9c7ykf FOREIGN KEY(alimento_id) REFERENCES alimento(id) NOCHECK;             
ALTER TABLE anthropometric_measurement ADD CONSTRAINT fk60b67csxpux28ndkpiotoa49n FOREIGN KEY(skinfolds_id) REFERENCES skinfolds(id) NOCHECK;             
ALTER TABLE clinical_exam ADD CONSTRAINT fkflo6kjqhd31peg2gvk0te3lnn FOREIGN KEY(liver_function_id) REFERENCES liver_function(id) NOCHECK;
ALTER TABLE alimento_ingesta ADD CONSTRAINT fkmksbm12t3bys3wvv2yt9ibvlj FOREIGN KEY(ingesta_id) REFERENCES ingesta(id) NOCHECK;           
ALTER TABLE platillo_ingesta ADD CONSTRAINT fk7auj7sxalkrof4n40nvpvh24g FOREIGN KEY(ingesta_id) REFERENCES ingesta(id) NOCHECK;           
ALTER TABLE alimento_ingesta ADD CONSTRAINT fkids1qxsho9c70iy66pmac84x FOREIGN KEY(alimento_id) REFERENCES alimento(id) NOCHECK;          
