






CREATE TABLE alimento (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    etanol real,
    fibra real,
    fosforo real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    peso_bruto_redondeado integer,
    peso_neto integer,
    potasio real,
    selenio real,
    sodio real,
    vita real,
    cant_sugerida real,
    clasificacion character varying(255) NOT NULL,
    nombre_alimento character varying(255) NOT NULL,
    unidad character varying(255)
);



ALTER TABLE alimento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alimento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE alimento_ingesta (
    id bigint NOT NULL,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    energia integer,
    etanol real,
    fibra real,
    fosforo real,
    hidratos_de_carbono real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    lipidos real,
    name character varying(255),
    peso_bruto_redondeado integer,
    peso_neto integer,
    portions integer,
    potasio real,
    proteina real,
    selenio real,
    sodio real,
    unidad character varying(255),
    vita real,
    alimento_id bigint,
    ingesta_id bigint
);



ALTER TABLE alimento_ingesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alimento_ingesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE anthropometric_measurement (
    id bigint NOT NULL,
    description text,
    measurement_date_time timestamp(6) without time zone NOT NULL,
    notes text,
    title character varying(200) NOT NULL,
    bioimpedance_id bigint,
    body_composition_id bigint,
    body_mass_id bigint,
    circumferences_id bigint,
    diameters_id bigint,
    paciente_id bigint NOT NULL,
    skinfolds_id bigint,
    activity_factor real,
    bmr_formula character varying(30),
    bmr_used real,
    get_kcal real,
    physical_activity_level character varying(30),
    tef_kcal real,
    total_adjusted_kcal real,
    final_total_kcal real,
    physiological_stress_active boolean,
    physiological_stress_type character varying(40),
    stress_factor_value real,
    stress_fever_temperature real,
    stress_formula_table character varying(30),
    stress_increment_mode character varying(30),
    stress_kcal real,
    stress_valid_from date,
    stress_valid_until date,
    CONSTRAINT anthropometric_measurement_bmr_formula_check CHECK (((bmr_formula)::text = ANY ((ARRAY['MIFFLIN_ST_JEOR'::character varying, 'HARRIS_BENEDICT'::character varying, 'FAO_WHO_ONU'::character varying, 'VALENCIA'::character varying, 'PROMEDIO'::character varying])::text[]))),
    CONSTRAINT anthropometric_measurement_physical_activity_level_check CHECK (((physical_activity_level)::text = ANY ((ARRAY['SEDENTARY'::character varying, 'LIGHT'::character varying, 'MODERATE'::character varying, 'INTENSE'::character varying, 'VERY_INTENSE'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT anthropometric_measurement_physiological_stress_type_check CHECK (((physiological_stress_type)::text = ANY ((ARRAY['NONE'::character varying, 'FEVER'::character varying, 'MINOR_SURGERY'::character varying, 'MAJOR_SURGERY'::character varying, 'MODERATE_INFECTION'::character varying, 'SEVERE_INFECTION'::character varying, 'SEPSIS'::character varying, 'TRAUMA'::character varying, 'BURNS'::character varying, 'CANCER'::character varying, 'FRACTURE'::character varying, 'POST_OPERATIVE'::character varying, 'MULTIPLE_TRAUMA'::character varying, 'HEAD_INJURY'::character varying, 'ORGAN_FAILURE'::character varying, 'PREGNANCY_COMPLICATION'::character varying, 'COPD_EXACERBATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT anthropometric_measurement_stress_formula_table_check CHECK (((stress_formula_table)::text = ANY ((ARRAY['LONG'::character varying, 'FEVER_PER_DEGREE'::character varying, 'ASPEN'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT anthropometric_measurement_stress_increment_mode_check CHECK (((stress_increment_mode)::text = ANY ((ARRAY['MULTIPLIER_BMR'::character varying, 'MULTIPLIER_GET'::character varying, 'FIXED_KCAL'::character varying])::text[])))
);



ALTER TABLE anthropometric_measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME anthropometric_measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE bioimpedance (
    id bigint NOT NULL,
    bioimpedance_value real,
    body_fat_percentage real,
    ecw_icw_ratio real,
    estimated_basal_metabolism real,
    extracellular_water real,
    fat_free_mass real,
    fat_mass real,
    impedance real,
    intracellular_water real,
    phase_angle real,
    reactance real,
    resistance real,
    skeletal_muscle_mass real,
    total_body_water_liters real,
    total_body_water_percentage real,
    bone_mass real,
    bone_mass_percentage real
);



ALTER TABLE bioimpedance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bioimpedance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE blood_chemistry (
    id bigint NOT NULL,
    bun real,
    creatinina real,
    glucosa real,
    hba1c real,
    urea real
);



ALTER TABLE blood_chemistry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME blood_chemistry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE body_composition (
    id bigint NOT NULL,
    indice_grasa_corporal real,
    porcentaje_grasa_corporal real,
    porcentaje_masa_muscular real,
    ectomorphy real,
    endomorphy real,
    mesomorphy real,
    somatocartax real,
    somatocartay real,
    metodo_obtencion character varying(30),
    masa_osea_kg real,
    porcentaje_masa_osea real,
    CONSTRAINT body_composition_metodo_obtencion_check CHECK (((metodo_obtencion)::text = ANY ((ARRAY['MANUAL'::character varying, 'BIOIMPEDANCIA'::character varying, 'PLIEGUES'::character varying, 'DEURENBERG'::character varying, 'DEXA'::character varying, 'OTRO'::character varying])::text[])))
);



ALTER TABLE body_composition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME body_composition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE body_mass (
    id bigint NOT NULL,
    body_mass_value real,
    height real,
    imc real,
    nivel_peso smallint,
    weight real,
    CONSTRAINT body_mass_height_check CHECK ((height <= (3)::double precision)),
    CONSTRAINT body_mass_nivel_peso_check CHECK (((nivel_peso >= 0) AND (nivel_peso <= 3))),
    CONSTRAINT body_mass_weight_check CHECK (((weight >= (10)::double precision) AND (weight <= (200)::double precision)))
);



ALTER TABLE body_mass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME body_mass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE body_metric_record (
    id bigint NOT NULL,
    body_fat_index real,
    body_fat_percentage real,
    height real,
    imc real,
    nivel_peso character varying(20),
    recorded_at timestamp(6) without time zone NOT NULL,
    source character varying(30) NOT NULL,
    source_id bigint NOT NULL,
    weight real,
    paciente_id bigint NOT NULL,
    bmr real,
    get_kcal real,
    tef_kcal real,
    total_adjusted_kcal real,
    metodo_obtencion_composicion character varying(30),
    CONSTRAINT body_metric_record_metodo_obtencion_composicion_check CHECK (((metodo_obtencion_composicion)::text = ANY ((ARRAY['MANUAL'::character varying, 'BIOIMPEDANCIA'::character varying, 'PLIEGUES'::character varying, 'DEURENBERG'::character varying, 'DEXA'::character varying, 'OTRO'::character varying])::text[]))),
    CONSTRAINT body_metric_record_nivel_peso_check CHECK (((nivel_peso)::text = ANY ((ARRAY['BAJO'::character varying, 'NORMAL'::character varying, 'ALTO'::character varying, 'SOBREPESO'::character varying])::text[]))),
    CONSTRAINT body_metric_record_source_check CHECK (((source)::text = ANY ((ARRAY['CONSULTATION'::character varying, 'ANTHROPOMETRIC'::character varying, 'CLINICAL_EXAM'::character varying])::text[])))
);



ALTER TABLE body_metric_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME body_metric_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE calendar_event (
    id bigint NOT NULL,
    description text,
    diastolica integer,
    duration_minutes integer NOT NULL,
    estatura real,
    event_date_time timestamp(6) without time zone NOT NULL,
    imc real,
    indice_glucemico integer,
    indice_grasa_corporal real,
    nivel_peso smallint,
    peso real,
    pulso integer,
    sistolica integer,
    spo2 real,
    status smallint NOT NULL,
    summary_notes text,
    temperatura real,
    title character varying(200) NOT NULL,
    paciente_id bigint NOT NULL,
    activity_factor real,
    bmr_formula character varying(30),
    bmr_used real,
    get_kcal real,
    physical_activity_level character varying(30),
    tef_kcal real,
    total_adjusted_kcal real,
    final_total_kcal real,
    physiological_stress_active boolean,
    physiological_stress_type character varying(40),
    stress_factor_value real,
    stress_fever_temperature real,
    stress_formula_table character varying(30),
    stress_increment_mode character varying(30),
    stress_kcal real,
    stress_valid_from date,
    stress_valid_until date,
    CONSTRAINT calendar_event_bmr_formula_check CHECK (((bmr_formula)::text = ANY ((ARRAY['MIFFLIN_ST_JEOR'::character varying, 'HARRIS_BENEDICT'::character varying, 'FAO_WHO_ONU'::character varying, 'VALENCIA'::character varying, 'PROMEDIO'::character varying])::text[]))),
    CONSTRAINT calendar_event_estatura_check CHECK ((estatura <= (3)::double precision)),
    CONSTRAINT calendar_event_nivel_peso_check CHECK (((nivel_peso >= 0) AND (nivel_peso <= 3))),
    CONSTRAINT calendar_event_peso_check CHECK (((peso >= (10)::double precision) AND (peso <= (200)::double precision))),
    CONSTRAINT calendar_event_physical_activity_level_check CHECK (((physical_activity_level)::text = ANY ((ARRAY['SEDENTARY'::character varying, 'LIGHT'::character varying, 'MODERATE'::character varying, 'INTENSE'::character varying, 'VERY_INTENSE'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT calendar_event_physiological_stress_type_check CHECK (((physiological_stress_type)::text = ANY ((ARRAY['NONE'::character varying, 'FEVER'::character varying, 'MINOR_SURGERY'::character varying, 'MAJOR_SURGERY'::character varying, 'MODERATE_INFECTION'::character varying, 'SEVERE_INFECTION'::character varying, 'SEPSIS'::character varying, 'TRAUMA'::character varying, 'BURNS'::character varying, 'CANCER'::character varying, 'FRACTURE'::character varying, 'POST_OPERATIVE'::character varying, 'MULTIPLE_TRAUMA'::character varying, 'HEAD_INJURY'::character varying, 'ORGAN_FAILURE'::character varying, 'PREGNANCY_COMPLICATION'::character varying, 'COPD_EXACERBATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT calendar_event_status_check CHECK (((status >= 0) AND (status <= 2))),
    CONSTRAINT calendar_event_stress_formula_table_check CHECK (((stress_formula_table)::text = ANY ((ARRAY['LONG'::character varying, 'FEVER_PER_DEGREE'::character varying, 'ASPEN'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT calendar_event_stress_increment_mode_check CHECK (((stress_increment_mode)::text = ANY ((ARRAY['MULTIPLIER_BMR'::character varying, 'MULTIPLIER_GET'::character varying, 'FIXED_KCAL'::character varying])::text[])))
);



ALTER TABLE calendar_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME calendar_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE circumferences (
    id bigint NOT NULL,
    ankle_circumference real,
    calf_circumference real,
    cephalic_circumference real,
    forearm_circumference real,
    hip_circumference real,
    mesosternal_circumference real,
    mid_thigh_circumference real,
    mid_upper_arm_circumference_contracted real,
    mid_upper_arm_circumference_relaxed real,
    neck_circumference real,
    thigh_circumference real,
    umbilical_circumference real,
    waist_circumference real,
    wrist_circumference real
);



ALTER TABLE circumferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME circumferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE clinical_exam (
    id bigint NOT NULL,
    description text,
    exam_date_time timestamp(6) without time zone NOT NULL,
    summary_notes text,
    title character varying(200) NOT NULL,
    blood_chemistry_id bigint,
    body_composition_id bigint,
    complete_blood_count_id bigint,
    lipid_profile_id bigint,
    liver_function_id bigint,
    other_tests_id bigint,
    paciente_id bigint NOT NULL,
    vital_signs_id bigint
);



ALTER TABLE clinical_exam ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME clinical_exam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE complete_blood_count (
    id bigint NOT NULL,
    hematocrito real,
    hemoglobina real,
    leucocitos real,
    plaquetas real
);



ALTER TABLE complete_blood_count ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME complete_blood_count_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE contact_inquiry (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    message character varying(2000) NOT NULL,
    name character varying(100) NOT NULL,
    read_by_admin boolean NOT NULL,
    subject character varying(200) NOT NULL
);



ALTER TABLE contact_inquiry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME contact_inquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE diameters (
    id bigint NOT NULL,
    anteroposterior_thorax_diameter real,
    biacromial_diameter real,
    biestiloid_wrist_diameter real,
    biiliocrestal_diameter real,
    bimaleolar_diameter real,
    femur_diameter real,
    foot_length real,
    hand_length real,
    humerus_diameter real,
    transverse_foot_diameter real,
    transverse_hand_diameter real,
    transverse_thorax_diameter real
);



ALTER TABLE diameters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME diameters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE dieta (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    nombre character varying(255),
    user_id character varying(255) NOT NULL
);



ALTER TABLE dieta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dieta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE ingesta (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    nombre character varying(255),
    dieta_id bigint
);



ALTER TABLE ingesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE ingrediente (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    etanol real,
    fibra real,
    fosforo real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    peso_bruto_redondeado integer,
    peso_neto integer,
    potasio real,
    selenio real,
    sodio real,
    vita real,
    cant_sugerida real,
    description character varying(255),
    unidad character varying(255),
    alimento_id bigint,
    platillo_id bigint NOT NULL
);



ALTER TABLE ingrediente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingrediente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE ingrediente_platillo_ingesta (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    etanol real,
    fibra real,
    fosforo real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    peso_bruto_redondeado integer,
    peso_neto integer,
    potasio real,
    selenio real,
    sodio real,
    vita real,
    cant_sugerida real,
    description character varying(255),
    unidad character varying(255),
    alimento_id bigint,
    platillo_id bigint NOT NULL
);



ALTER TABLE ingrediente_platillo_ingesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingrediente_platillo_ingesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE lipid_profile (
    id bigint NOT NULL,
    colesterol_total real,
    hdl real,
    ldl real,
    trigliceridos real
);



ALTER TABLE lipid_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lipid_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE liver_function (
    id bigint NOT NULL,
    alt real,
    ast real,
    bilirrubina real
);



ALTER TABLE liver_function ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME liver_function_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE nutritionist_profile (
    id bigint NOT NULL,
    cedula_profesional character varying(20),
    display_name character varying(100),
    logo_extension character varying(10),
    registro timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);



ALTER TABLE nutritionist_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME nutritionist_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE other_indicators (
    id bigint NOT NULL,
    ferritina real,
    hierro real,
    vitaminab12 real,
    vitaminad real
);



ALTER TABLE other_indicators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME other_indicators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE paciente (
    id bigint NOT NULL,
    bmr real,
    dob date NOT NULL,
    email character varying(100),
    estatura real,
    gender character varying(1) NOT NULL,
    imc real,
    name character varying(100) NOT NULL,
    nivel_peso smallint,
    parentesco character varying(255),
    peso real,
    phone character varying(25),
    pregnancy boolean,
    registro timestamp(6) without time zone,
    responsible_name character varying(100),
    user_id character varying(255) NOT NULL,
    patient_auth_sub character varying(255),
    get_kcal real,
    tef_kcal real,
    total_adjusted_kcal real,
    final_total_kcal real,
    stress_kcal real,
    CONSTRAINT paciente_nivel_peso_check CHECK (((nivel_peso >= 0) AND (nivel_peso <= 3)))
);



CREATE TABLE paciente_dieta (
    id bigint NOT NULL,
    end_date date,
    notes text,
    start_date date NOT NULL,
    status smallint NOT NULL,
    dieta_id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    CONSTRAINT paciente_dieta_status_check CHECK (((status >= 0) AND (status <= 2)))
);



ALTER TABLE paciente_dieta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME paciente_dieta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE paciente_energy_preferences (
    id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    activity_factor_scale character varying(30),
    preferred_bmr_formula character varying(30),
    physical_activity_level character varying(30),
    activity_factor double precision,
    custom_factor_sedentary double precision,
    custom_factor_light double precision,
    custom_factor_moderate double precision,
    custom_factor_intense double precision,
    custom_factor_very_intense double precision,
    physiological_stress_active boolean DEFAULT false,
    physiological_stress_type character varying(40),
    stress_formula_table character varying(30),
    stress_increment_mode character varying(30),
    stress_factor_value double precision,
    stress_valid_from date,
    stress_valid_until date,
    stress_fever_temperature double precision,
    tef_method character varying(30),
    tef_base character varying(30),
    tef_fixed_percent double precision,
    tef_macro_protein_percent double precision,
    tef_macro_carbs_percent double precision,
    tef_macro_fat_percent double precision
);



CREATE SEQUENCE paciente_energy_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE paciente_energy_preferences_id_seq OWNED BY paciente_energy_preferences.id;



ALTER TABLE paciente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME paciente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE paciente_medical_history (
    id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    antecedentes_prenatales text,
    antecedentes_natales text,
    antecedentes_patologicos_personales text,
    antecedentes_patologicos_familiares text,
    complicaciones text,
    tipo_sanguineo character varying(4),
    historial_alimenticio text,
    desarrollo_psicomotor text,
    alergias text,
    hipertension boolean DEFAULT false,
    diabetes boolean DEFAULT false,
    hipotiroidismo boolean DEFAULT false,
    obesidad boolean DEFAULT false,
    anemia boolean DEFAULT false,
    bulimia boolean DEFAULT false,
    anorexia boolean DEFAULT false,
    enfermedades_hepaticas boolean DEFAULT false
);



CREATE SEQUENCE paciente_medical_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE paciente_medical_history_id_seq OWNED BY paciente_medical_history.id;



CREATE TABLE patient_message (
    id bigint NOT NULL,
    body character varying(2000) NOT NULL,
    nutritionist_user_id character varying(255) NOT NULL,
    read_by_patient boolean NOT NULL,
    sender_role character varying(20) NOT NULL,
    sent_at timestamp(6) with time zone NOT NULL,
    paciente_id bigint NOT NULL,
    read_by_nutritionist boolean NOT NULL,
    CONSTRAINT patient_message_sender_role_check CHECK (((sender_role)::text = ANY ((ARRAY['PATIENT'::character varying, 'NUTRITIONIST'::character varying])::text[])))
);



ALTER TABLE patient_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME patient_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE platillo (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    etanol real,
    fibra real,
    fosforo real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    peso_bruto_redondeado integer,
    peso_neto integer,
    potasio real,
    selenio real,
    sodio real,
    vita real,
    description character varying(255),
    image_url character varying(255),
    ingestas_sugeridas character varying(255),
    name character varying(255),
    pdf_url character varying(255),
    video_url character varying(255)
);



ALTER TABLE platillo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME platillo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE platillo_ingesta (
    id bigint NOT NULL,
    energia integer,
    hidratos_de_carbono real,
    lipidos real,
    proteina real,
    acido_ascorbico real,
    acido_folico real,
    ag_monoinsaturados real,
    ag_poliinsaturados real,
    ag_saturados real,
    azucar_por_equivalente real,
    calcio real,
    carga_glicemica real,
    colesterol real,
    etanol real,
    fibra real,
    fosforo real,
    hierro real,
    hierro_no_hem real,
    indice_glicemico real,
    peso_bruto_redondeado integer,
    peso_neto integer,
    potasio real,
    selenio real,
    sodio real,
    vita real,
    image_url character varying(255),
    name character varying(255),
    pdf_url character varying(255),
    portions integer,
    recommendations character varying(255),
    video_url character varying(255),
    ingesta_id bigint
);



ALTER TABLE platillo_ingesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME platillo_ingesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE seed_platillo (
    name character varying(255) NOT NULL,
    description character varying(510),
    ingestas_sugeridas character varying(255)
);



CREATE TABLE seed_platillo_ingrediente (
    id bigint NOT NULL,
    platillo_name character varying(255) NOT NULL,
    alimento_nombre character varying(255) NOT NULL,
    alimento_id bigint,
    peso_neto integer NOT NULL,
    orden integer DEFAULT 1 NOT NULL
);



CREATE SEQUENCE seed_platillo_ingrediente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE seed_platillo_ingrediente_id_seq OWNED BY seed_platillo_ingrediente.id;



CREATE TABLE skinfolds (
    id bigint NOT NULL,
    abdominal_skinfold real,
    biceps_skinfold real,
    frontal_thigh_skinfold real,
    iliac_crest_skinfold real,
    medial_axillary_skinfold real,
    medial_calf_skinfold real,
    pectoral_skinfold real,
    subscapular_skinfold real,
    supraespinal_skinfold real,
    triceps_skinfold real
);



ALTER TABLE skinfolds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME skinfolds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE spring_session (
    primary_id character(36) NOT NULL,
    session_id character(36) NOT NULL,
    creation_time bigint NOT NULL,
    last_access_time bigint NOT NULL,
    max_inactive_interval integer NOT NULL,
    expiry_time bigint NOT NULL,
    principal_name character varying(100)
);



CREATE TABLE spring_session_attributes (
    session_primary_id character(36) NOT NULL,
    attribute_name character varying(200) NOT NULL,
    attribute_bytes bytea NOT NULL
);



CREATE TABLE vital_signs (
    id bigint NOT NULL,
    diastolica integer,
    estatura real,
    imc real,
    indice_glucemico integer,
    nivel_peso smallint,
    peso real,
    pulso integer,
    sistolica integer,
    spo2 real,
    temperatura real,
    CONSTRAINT vital_signs_estatura_check CHECK ((estatura <= (3)::double precision)),
    CONSTRAINT vital_signs_nivel_peso_check CHECK (((nivel_peso >= 0) AND (nivel_peso <= 3))),
    CONSTRAINT vital_signs_peso_check CHECK (((peso >= (10)::double precision) AND (peso <= (200)::double precision)))
);



ALTER TABLE vital_signs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME vital_signs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY paciente_energy_preferences ALTER COLUMN id SET DEFAULT nextval('paciente_energy_preferences_id_seq'::regclass);



ALTER TABLE ONLY paciente_medical_history ALTER COLUMN id SET DEFAULT nextval('paciente_medical_history_id_seq'::regclass);



ALTER TABLE ONLY seed_platillo_ingrediente ALTER COLUMN id SET DEFAULT nextval('seed_platillo_ingrediente_id_seq'::regclass);



ALTER TABLE ONLY alimento_ingesta
    ADD CONSTRAINT alimento_ingesta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY alimento
    ADD CONSTRAINT alimento_pkey PRIMARY KEY (id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT anthropometric_measurement_pkey PRIMARY KEY (id);



ALTER TABLE ONLY bioimpedance
    ADD CONSTRAINT bioimpedance_pkey PRIMARY KEY (id);



ALTER TABLE ONLY blood_chemistry
    ADD CONSTRAINT blood_chemistry_pkey PRIMARY KEY (id);



ALTER TABLE ONLY body_composition
    ADD CONSTRAINT body_composition_pkey PRIMARY KEY (id);



ALTER TABLE ONLY body_mass
    ADD CONSTRAINT body_mass_pkey PRIMARY KEY (id);



ALTER TABLE ONLY body_metric_record
    ADD CONSTRAINT body_metric_record_pkey PRIMARY KEY (id);



ALTER TABLE ONLY calendar_event
    ADD CONSTRAINT calendar_event_pkey PRIMARY KEY (id);



ALTER TABLE ONLY circumferences
    ADD CONSTRAINT circumferences_pkey PRIMARY KEY (id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT clinical_exam_pkey PRIMARY KEY (id);



ALTER TABLE ONLY complete_blood_count
    ADD CONSTRAINT complete_blood_count_pkey PRIMARY KEY (id);



ALTER TABLE ONLY contact_inquiry
    ADD CONSTRAINT contact_inquiry_pkey PRIMARY KEY (id);



ALTER TABLE ONLY diameters
    ADD CONSTRAINT diameters_pkey PRIMARY KEY (id);



ALTER TABLE ONLY dieta
    ADD CONSTRAINT dieta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY ingesta
    ADD CONSTRAINT ingesta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY ingrediente
    ADD CONSTRAINT ingrediente_pkey PRIMARY KEY (id);



ALTER TABLE ONLY ingrediente_platillo_ingesta
    ADD CONSTRAINT ingrediente_platillo_ingesta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY lipid_profile
    ADD CONSTRAINT lipid_profile_pkey PRIMARY KEY (id);



ALTER TABLE ONLY liver_function
    ADD CONSTRAINT liver_function_pkey PRIMARY KEY (id);



ALTER TABLE ONLY nutritionist_profile
    ADD CONSTRAINT nutritionist_profile_pkey PRIMARY KEY (id);



ALTER TABLE ONLY other_indicators
    ADD CONSTRAINT other_indicators_pkey PRIMARY KEY (id);



ALTER TABLE ONLY paciente_dieta
    ADD CONSTRAINT paciente_dieta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY paciente_energy_preferences
    ADD CONSTRAINT paciente_energy_preferences_paciente_id_key UNIQUE (paciente_id);



ALTER TABLE ONLY paciente_energy_preferences
    ADD CONSTRAINT paciente_energy_preferences_pkey PRIMARY KEY (id);



ALTER TABLE ONLY paciente_medical_history
    ADD CONSTRAINT paciente_medical_history_paciente_id_key UNIQUE (paciente_id);



ALTER TABLE ONLY paciente_medical_history
    ADD CONSTRAINT paciente_medical_history_pkey PRIMARY KEY (id);



ALTER TABLE ONLY paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id);



ALTER TABLE ONLY patient_message
    ADD CONSTRAINT patient_message_pkey PRIMARY KEY (id);



ALTER TABLE ONLY platillo_ingesta
    ADD CONSTRAINT platillo_ingesta_pkey PRIMARY KEY (id);



ALTER TABLE ONLY platillo
    ADD CONSTRAINT platillo_pkey PRIMARY KEY (id);



ALTER TABLE ONLY seed_platillo_ingrediente
    ADD CONSTRAINT seed_platillo_ingrediente_pkey PRIMARY KEY (id);



ALTER TABLE ONLY seed_platillo
    ADD CONSTRAINT seed_platillo_pkey PRIMARY KEY (name);



ALTER TABLE ONLY skinfolds
    ADD CONSTRAINT skinfolds_pkey PRIMARY KEY (id);



ALTER TABLE ONLY spring_session_attributes
    ADD CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name);



ALTER TABLE ONLY spring_session
    ADD CONSTRAINT spring_session_pk PRIMARY KEY (primary_id);



ALTER TABLE ONLY nutritionist_profile
    ADD CONSTRAINT uk1qnn4b81jl8k09srmc1qffdaf UNIQUE (user_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT uk2fawyoyso93qu56a4kwccyc4i UNIQUE (body_mass_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT uk4yp3v3ua0g8f0r95kr4bndrua UNIQUE (skinfolds_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT uk5d7cxjek0dw1j8ybdt5y9nq0c UNIQUE (blood_chemistry_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT uk796r3duhqp0t7u9426mco4su1 UNIQUE (vital_signs_id);



ALTER TABLE ONLY paciente
    ADD CONSTRAINT uk8fyw62tyrdfdatc55cxupobud UNIQUE (patient_auth_sub);



ALTER TABLE ONLY body_metric_record
    ADD CONSTRAINT uk_body_metric_source UNIQUE (source, source_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT ukae015460p5sv42hrmssblbvf9 UNIQUE (body_composition_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT ukaimqrlwna5yjdx99k41lni5ef UNIQUE (complete_blood_count_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT ukcu2gpan9l5x7ivnqvuj9n0upl UNIQUE (circumferences_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT ukfegexrmshur33hh779x6mj94l UNIQUE (other_tests_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT ukg08kxin6n9y36bnov4rw920kj UNIQUE (body_composition_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT ukh4tk9939hjtbfcvfsi90yrjmb UNIQUE (diameters_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT ukkkrs9fv0ptn525bk1qr7ui2fj UNIQUE (lipid_profile_id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT ukrd298hwi24qog8vsc5dni0kvo UNIQUE (liver_function_id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT uksttyncx5svbba5jda5haod7c UNIQUE (bioimpedance_id);



ALTER TABLE ONLY vital_signs
    ADD CONSTRAINT vital_signs_pkey PRIMARY KEY (id);



CREATE INDEX idx_body_metric_paciente_date ON body_metric_record USING btree (paciente_id, recorded_at);



CREATE UNIQUE INDEX spring_session_ix1 ON spring_session USING btree (session_id);



CREATE INDEX spring_session_ix2 ON spring_session USING btree (expiry_time);



CREATE INDEX spring_session_ix3 ON spring_session USING btree (principal_name);



ALTER TABLE ONLY body_metric_record
    ADD CONSTRAINT fk1mhwqjctg0c4n5vrb11o513sk FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fk5f4r6a26tipmwt2tnwo3l8dwg FOREIGN KEY (body_composition_id) REFERENCES body_composition(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fk60b67csxpux28ndkpiotoa49n FOREIGN KEY (skinfolds_id) REFERENCES skinfolds(id);



ALTER TABLE ONLY platillo_ingesta
    ADD CONSTRAINT fk7auj7sxalkrof4n40nvpvh24g FOREIGN KEY (ingesta_id) REFERENCES ingesta(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fk7xaek5paff0n52u4jdcs1ggif FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY ingrediente
    ADD CONSTRAINT fk8a4qhtoiupu5ypatjb4jhhaar FOREIGN KEY (platillo_id) REFERENCES platillo(id);



ALTER TABLE ONLY ingrediente_platillo_ingesta
    ADD CONSTRAINT fk8l3062isqed3yp8rq1d9c7ykf FOREIGN KEY (alimento_id) REFERENCES alimento(id);



ALTER TABLE ONLY ingrediente_platillo_ingesta
    ADD CONSTRAINT fk8wl4p7y8o17v9v018pfu0spsm FOREIGN KEY (platillo_id) REFERENCES platillo_ingesta(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fka6iussy2olww2ypyaur6pxmom FOREIGN KEY (body_mass_id) REFERENCES body_mass(id);



ALTER TABLE ONLY calendar_event
    ADD CONSTRAINT fkc8wt5obt6gpde15em13djjp1h FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkcuiqsadj9juhbc8kxolrgnn0 FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkf23fwfcpjpypxwlnxsqd8l18k FOREIGN KEY (vital_signs_id) REFERENCES vital_signs(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkflo6kjqhd31peg2gvk0te3lnn FOREIGN KEY (liver_function_id) REFERENCES liver_function(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fkhuex07009t8bi872lgshasnan FOREIGN KEY (body_composition_id) REFERENCES body_composition(id);



ALTER TABLE ONLY alimento_ingesta
    ADD CONSTRAINT fkids1qxsho9c70iy66pmac84x FOREIGN KEY (alimento_id) REFERENCES alimento(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkjfvoxbd2f2dgdveias0gvic90 FOREIGN KEY (blood_chemistry_id) REFERENCES blood_chemistry(id);



ALTER TABLE ONLY paciente_dieta
    ADD CONSTRAINT fkjjtyabhrqrvc3ki64m7jpi1hx FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY ingesta
    ADD CONSTRAINT fkjtyojiau15wr5cmu9cc8wsn26 FOREIGN KEY (dieta_id) REFERENCES dieta(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkmhoaojsdrjfwiax0h07qwluln FOREIGN KEY (lipid_profile_id) REFERENCES lipid_profile(id);



ALTER TABLE ONLY alimento_ingesta
    ADD CONSTRAINT fkmksbm12t3bys3wvv2yt9ibvlj FOREIGN KEY (ingesta_id) REFERENCES ingesta(id);



ALTER TABLE ONLY patient_message
    ADD CONSTRAINT fkmrlmm09ccos69d09vtu8u7l6j FOREIGN KEY (paciente_id) REFERENCES paciente(id);



ALTER TABLE ONLY ingrediente
    ADD CONSTRAINT fknknqox49l28rbby5d80fynjmy FOREIGN KEY (alimento_id) REFERENCES alimento(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fkp6ih6ousocjrju2ikqv1ya9rv FOREIGN KEY (other_tests_id) REFERENCES other_indicators(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fkpw614ghhr0ci91jxfgc4xx2l6 FOREIGN KEY (diameters_id) REFERENCES diameters(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fkqixumudvlkx188wvcjg4ri5fi FOREIGN KEY (bioimpedance_id) REFERENCES bioimpedance(id);



ALTER TABLE ONLY paciente_dieta
    ADD CONSTRAINT fkr29oahehxp6oglwlxq7avo9u8 FOREIGN KEY (dieta_id) REFERENCES dieta(id);



ALTER TABLE ONLY anthropometric_measurement
    ADD CONSTRAINT fksar6y6g775mycb6xtftkhjatf FOREIGN KEY (circumferences_id) REFERENCES circumferences(id);



ALTER TABLE ONLY clinical_exam
    ADD CONSTRAINT fksfwdo95r563hhdih2vfwt056c FOREIGN KEY (complete_blood_count_id) REFERENCES complete_blood_count(id);



ALTER TABLE ONLY paciente_energy_preferences
    ADD CONSTRAINT paciente_energy_preferences_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES paciente(id) ON DELETE CASCADE;



ALTER TABLE ONLY paciente_medical_history
    ADD CONSTRAINT paciente_medical_history_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES paciente(id) ON DELETE CASCADE;



ALTER TABLE ONLY seed_platillo_ingrediente
    ADD CONSTRAINT seed_platillo_ingrediente_platillo_name_fkey FOREIGN KEY (platillo_name) REFERENCES seed_platillo(name) ON DELETE CASCADE;



ALTER TABLE ONLY spring_session_attributes
    ADD CONSTRAINT spring_session_attributes_fk FOREIGN KEY (session_primary_id) REFERENCES spring_session(primary_id) ON DELETE CASCADE;




